var _s_w_i_g_t_y_p_e__p___logging_context_____logging_context_pimpl_8cs =
[
    [ "LlamaLibrary.SWIGTYPE_p_LoggingContext__LoggingContextPimpl", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___logging_context_____logging_context_pimpl.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___logging_context_____logging_context_pimpl" ]
];