var annotated_dup =
[
    [ "LlamaLibrary", "namespace_llama_library.html", [
      [ "AsyncLlamaInfrence", "class_llama_library_1_1_async_llama_infrence.html", "class_llama_library_1_1_async_llama_infrence" ],
      [ "CallbackWrapper", "class_llama_library_1_1_callback_wrapper.html", "class_llama_library_1_1_callback_wrapper" ],
      [ "FileWrapper", "class_llama_library_1_1_file_wrapper.html", "class_llama_library_1_1_file_wrapper" ],
      [ "gpt_params", "class_llama_library_1_1gpt__params.html", "class_llama_library_1_1gpt__params" ],
      [ "Int32s", "class_llama_library_1_1_int32s.html", "class_llama_library_1_1_int32s" ],
      [ "libllama_lib", "class_llama_library_1_1libllama__lib.html", "class_llama_library_1_1libllama__lib" ],
      [ "libllama_libPINVOKE", "class_llama_library_1_1libllama__lib_p_i_n_v_o_k_e.html", "class_llama_library_1_1libllama__lib_p_i_n_v_o_k_e" ],
      [ "llama_sampling_params", "class_llama_library_1_1llama__sampling__params.html", "class_llama_library_1_1llama__sampling__params" ],
      [ "LlamaControlVectorLoadInfos", "class_llama_library_1_1_llama_control_vector_load_infos.html", "class_llama_library_1_1_llama_control_vector_load_infos" ],
      [ "LlamaInfrence", "class_llama_library_1_1_llama_infrence.html", "class_llama_library_1_1_llama_infrence" ],
      [ "LoggingContext", "class_llama_library_1_1_logging_context.html", "class_llama_library_1_1_logging_context" ],
      [ "StringAndFloat", "class_llama_library_1_1_string_and_float.html", "class_llama_library_1_1_string_and_float" ],
      [ "Strings", "class_llama_library_1_1_strings.html", "class_llama_library_1_1_strings" ],
      [ "StringsAndFloats", "class_llama_library_1_1_strings_and_floats.html", "class_llama_library_1_1_strings_and_floats" ],
      [ "SWIGTYPE_p_AsyncLlamaInfrence__LlamaAsyncImpl", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___async_llama_infrence_____llama_async_impl.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___async_llama_infrence_____llama_async_impl" ],
      [ "SWIGTYPE_p_float", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__float.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__float" ],
      [ "SWIGTYPE_p_ggml_backend_sched_eval_callback", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__ggml__backend__sched__eval__callback.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__ggml__backend__sched__eval__callback" ],
      [ "SWIGTYPE_p_ggml_numa_strategy", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__ggml__numa__strategy.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__ggml__numa__strategy" ],
      [ "SWIGTYPE_p_llama_control_vector_load_info", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__llama__control__vector__load__info.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__llama__control__vector__load__info" ],
      [ "SWIGTYPE_p_llama_sampling_params", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__llama__sampling__params.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__llama__sampling__params" ],
      [ "SWIGTYPE_p_LlamaInfrence__LlamaImpl", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___llama_infrence_____llama_impl.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___llama_infrence_____llama_impl" ],
      [ "SWIGTYPE_p_LoggingContext__LoggingContextPimpl", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___logging_context_____logging_context_pimpl.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p___logging_context_____logging_context_pimpl" ],
      [ "SWIGTYPE_p_std__unordered_mapT_llama_token_float_t", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____unordered__map_t__llama__token__float__t.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____unordered__map_t__llama__token__float__t" ],
      [ "SWIGTYPE_p_std__vectorT_llama_model_kv_override_t", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__llama__model__kv__override__t.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__llama__model__kv__override__t" ],
      [ "SWIGTYPE_p_std__vectorT_llama_sampler_type_t", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__llama__sampler__type__t.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__llama__sampler__type__t" ],
      [ "SWIGTYPE_p_std__vectorT_llama_token_t", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__llama__token__t.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__llama__token__t" ],
      [ "SWIGTYPE_p_std__vectorT_std__tupleT_std__string_float_t_t", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__std____tuple_t__std____string__float__t__t.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__std____vector_t__std____tuple_t__std____string__float__t__t" ],
      [ "SWIGTYPE_p_void", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__void.html", "class_llama_library_1_1_s_w_i_g_t_y_p_e__p__void" ]
    ] ],
    [ "AddFrameworksPostBuild", "class_add_frameworks_post_build.html", "class_add_frameworks_post_build" ],
    [ "BasicGptParamsSettings", "class_basic_gpt_params_settings.html", "class_basic_gpt_params_settings" ],
    [ "BasicGptParamsSettingsEditor", "class_basic_gpt_params_settings_editor.html", "class_basic_gpt_params_settings_editor" ],
    [ "BinaryAsset", "class_binary_asset.html", "class_binary_asset" ],
    [ "CharacterAnimationTrigger", "class_character_animation_trigger.html", "class_character_animation_trigger" ],
    [ "CharacterStyleMapper", "class_character_style_mapper.html", "class_character_style_mapper" ],
    [ "CircularMotion", "class_circular_motion.html", "class_circular_motion" ],
    [ "DialogManager", "class_dialog_manager.html", "class_dialog_manager" ],
    [ "DialogTextAndCharacterStylesResetter", "class_dialog_text_and_character_styles_resetter.html", "class_dialog_text_and_character_styles_resetter" ],
    [ "DialogTextMapper", "class_dialog_text_mapper.html", "class_dialog_text_mapper" ],
    [ "DisableWhileNotConfigured", "class_disable_while_not_configured.html", "class_disable_while_not_configured" ],
    [ "EnableWebGLMultithreading", "class_enable_web_g_l_multithreading.html", "class_enable_web_g_l_multithreading" ],
    [ "GGUFImporter", "class_g_g_u_f_importer.html", "class_g_g_u_f_importer" ],
    [ "LogToUI", "class_log_to_u_i.html", "class_log_to_u_i" ],
    [ "MinimalExample", "class_minimal_example.html", "class_minimal_example" ],
    [ "ModelController", "class_model_controller.html", "class_model_controller" ],
    [ "OrbitCamera", "class_orbit_camera.html", "class_orbit_camera" ],
    [ "PrintGeneratedText", "class_print_generated_text.html", "class_print_generated_text" ],
    [ "PrintModelState", "class_print_model_state.html", "class_print_model_state" ],
    [ "PrintStartModelTokensToGenerate", "class_print_start_model_tokens_to_generate.html", "class_print_start_model_tokens_to_generate" ],
    [ "PrintStopwatchScore", "class_print_stopwatch_score.html", "class_print_stopwatch_score" ],
    [ "RandomColor", "class_random_color.html", "class_random_color" ],
    [ "RandomSpin", "class_random_spin.html", "class_random_spin" ],
    [ "RunModelAsync", "class_run_model_async.html", "class_run_model_async" ],
    [ "SetStringValueFromFloat", "class_set_string_value_from_float.html", "class_set_string_value_from_float" ]
];