StyledLines from testedlines.com: C# docs: MinimalExample Class Reference
MinimalExample Class Reference
Public Attributes
BinaryAsset binaryFileAsset
Public variable to hold a reference to the binary asset containing the model's data.
Private Member Functions
IEnumerator GenerateLine ()
Coroutine to handle the asynchronous generation of text from the language model. Coroutines allow the function to pause execution and resume later, making it perfect for waiting on asynchronous operations.
void Start ()
The Start method is called when the script instance is being loaded. It initializes the ModelController with the binary file asset and starts the generation process.
Private Attributes
ModelController _llmController = null
Private variable to hold an instance of the ModelController class. This controller will manage the interaction with the language model.
Member Function Documentation
GenerateLine()
IEnumerator MinimalExample.GenerateLine () private
Coroutine to handle the asynchronous generation of text from the language model. Coroutines allow the function to pause execution and resume later, making it perfect for waiting on asynchronous operations.
Returns
References _llmController, ModelController.ExtractFirstPart(), LlamaLibrary.AsyncLlamaInfrence.GenerateAsync(), LlamaLibrary.AsyncLlamaInfrence.GetGenerationResults(), LlamaLibrary.AsyncLlamaInfrence.IsGenerationReady(), and ModelController.model.
Referenced by Start().
Start()
void MinimalExample.Start () private
The Start method is called when the script instance is being loaded. It initializes the ModelController with the binary file asset and starts the generation process.
References _llmController, binaryFileAsset, and GenerateLine().
Member Data Documentation
_llmController
ModelController MinimalExample._llmController = null private
Private variable to hold an instance of the ModelController class. This controller will manage the interaction with the language model.
Referenced by GenerateLine(), and Start().
binaryFileAsset
BinaryAsset MinimalExample.binaryFileAsset
Public variable to hold a reference to the binary asset containing the model's data.
Referenced by Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrenceUnity/MinimalExample.cs