StyledLines from testedlines.com: C# docs: LlamaLibrary.StringAndFloat Class Reference
LlamaLibrary.StringAndFloat Class Reference
Public Member Functions
virtual void Dispose ()
StringAndFloat ()
StringAndFloat (string t, float u)
StringAndFloat (StringAndFloat p)
Protected Attributes
bool swigCMemOwn
Package Functions
StringAndFloat (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (StringAndFloat obj)
Properties
string first [get, set]
float second [get, set]
Private Member Functions
~StringAndFloat ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
StringAndFloat() [1/4]
LlamaLibrary.StringAndFloat.StringAndFloat (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.StringAndFloat.swigCMemOwn, and LlamaLibrary.StringAndFloat.swigCPtr.
~StringAndFloat()
LlamaLibrary.StringAndFloat.~StringAndFloat () private
References LlamaLibrary.StringAndFloat.Dispose().
StringAndFloat() [2/4]
LlamaLibrary.StringAndFloat.StringAndFloat ()
StringAndFloat() [3/4]
LlamaLibrary.StringAndFloat.StringAndFloat (string t, float u)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
StringAndFloat() [4/4]
LlamaLibrary.StringAndFloat.StringAndFloat (StringAndFloat p)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Member Function Documentation
Dispose()
virtual void LlamaLibrary.StringAndFloat.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_StringAndFloat(), LlamaLibrary.StringAndFloat.swigCMemOwn, and LlamaLibrary.StringAndFloat.swigCPtr.
Referenced by LlamaLibrary.StringAndFloat.~StringAndFloat().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.StringAndFloat.getCPtr (StringAndFloat obj) static package
References LlamaLibrary.StringAndFloat.swigCPtr.
Referenced by LlamaLibrary.StringsAndFloats.Add(), LlamaLibrary.StringsAndFloats.Insert(), LlamaLibrary.StringsAndFloats.Repeat(), and LlamaLibrary.StringsAndFloats.setitem().
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.StringAndFloat.swigCMemOwn protected
Referenced by LlamaLibrary.StringAndFloat.Dispose(), and LlamaLibrary.StringAndFloat.StringAndFloat().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.StringAndFloat.swigCPtr private
Referenced by LlamaLibrary.StringAndFloat.Dispose(), LlamaLibrary.StringAndFloat.getCPtr(), and LlamaLibrary.StringAndFloat.StringAndFloat().
Property Documentation
first
string LlamaLibrary.StringAndFloat.first get set
second
float LlamaLibrary.StringAndFloat.second get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/StringAndFloat.cs