StyledLines from testedlines.com: C# docs: CharacterStyleMapper Class Reference
CharacterStyleMapper Class Reference
Private Member Functions
void OnCharacterSelected (int selectedIndex)
void OnStyleChanged (string newStyle)
void SetStyleInputField (string style)
void Start ()
Private Attributes
TMP_Dropdown characterDropdown
DialogManager dialogManager
TMP_InputField styleInputField
Member Function Documentation
OnCharacterSelected()
void CharacterStyleMapper.OnCharacterSelected (int selectedIndex) private
References characterDropdown, DialogManager.Characters, dialogManager, and SetStyleInputField().
Referenced by Start().
OnStyleChanged()
void CharacterStyleMapper.OnStyleChanged (string newStyle) private
References characterDropdown, DialogManager.Characters, and dialogManager.
Referenced by Start().
SetStyleInputField()
void CharacterStyleMapper.SetStyleInputField (string style) private
Referenced by OnCharacterSelected(), and Start().
Start()
void CharacterStyleMapper.Start () private
References characterDropdown, DialogManager.Characters, dialogManager, OnCharacterSelected(), OnStyleChanged(), SetStyleInputField(), and styleInputField.
Member Data Documentation
characterDropdown
TMP_Dropdown CharacterStyleMapper.characterDropdown private
Referenced by OnCharacterSelected(), OnStyleChanged(), and Start().
dialogManager
DialogManager CharacterStyleMapper.dialogManager private
Referenced by OnCharacterSelected(), OnStyleChanged(), and Start().
styleInputField
TMP_InputField CharacterStyleMapper.styleInputField private
Referenced by Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/DialogUtils/CharacterStyleMapper.cs