StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText Class Reference
Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText Class Reference
Public Attributes
RunModelAsync StateController
TMP_Text UiObject
Private Member Functions
void OnDestroy ()
void OnStateChanged (string text)
void Start ()
Member Function Documentation
OnDestroy()
void Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.OnDestroy () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedComplete, Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedOutputChanged, Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.OnStateChanged(), and Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.StateController.
OnStateChanged()
void Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.OnStateChanged (string text) private
Referenced by Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.Start().
Start()
void Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.Start () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedComplete, Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedOutputChanged, Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.OnStateChanged(), and Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.StateController.
Member Data Documentation
StateController
RunModelAsync Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.StateController
Referenced by Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.Start().
UiObject
TMP_Text Assets.StyledLines.Runtime.UIHelpers.PrintGeneratedText.UiObject
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/PrintGeneratedText.cs