StyledLines from testedlines.com: C# docs: LlamaLibrary.Int32s Class Reference
LlamaLibrary.Int32s Class Reference
Classes
class Int32sEnumerator
Public Member Functions
void Add (int x)
void AddRange (Int32s values)
void Clear ()
bool Contains (int value)
void CopyTo (int index, int[] array, int arrayIndex, int count)
void CopyTo (int[] array)
void CopyTo (int[] array, int arrayIndex)
virtual void Dispose ()
Int32sEnumerator GetEnumerator ()
Int32s GetRange (int index, int count)
int IndexOf (int value)
void Insert (int index, int x)
void InsertRange (int index, Int32s values)
Int32s ()
Int32s (global::System.Collections.Generic.IEnumerable< int > c)
Int32s (global::System.Collections.IEnumerable c)
Int32s (int capacity)
Int32s (Int32s other)
int LastIndexOf (int value)
bool Remove (int value)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, Int32s values)
int[] ToArray ()
Static Public Member Functions
static Int32s Repeat (int value, int count)
Protected Attributes
bool swigCMemOwn
Package Functions
Int32s (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (Int32s obj)
Properties
int Capacity [get, set]
int Count [get]
bool IsFixedSize [get]
bool IsReadOnly [get]
bool IsSynchronized [get]
int this[int index] [get, set]
Private Member Functions
uint capacity ()
global::System.Collections.Generic.IEnumerator< int > global::System.Collections.Generic.IEnumerable< int >. GetEnumerator ()
global::System.Collections.IEnumerator global::System.Collections.IEnumerable. GetEnumerator ()
int getitem (int index)
int getitemcopy (int index)
void reserve (uint n)
void setitem (int index, int value)
uint size ()
~Int32s ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
Int32s() [1/6]
LlamaLibrary.Int32s.Int32s (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.Int32s.swigCMemOwn, and LlamaLibrary.Int32s.swigCPtr.
~Int32s()
LlamaLibrary.Int32s.~Int32s () private
References LlamaLibrary.Int32s.Dispose().
Int32s() [2/6]
LlamaLibrary.Int32s.Int32s (global::System::Collections::IEnumerable c)
References LlamaLibrary.Int32s.Add().
Int32s() [3/6]
LlamaLibrary.Int32s.Int32s (global::System::Collections::Generic::IEnumerable< int > c)
References LlamaLibrary.Int32s.Add().
Int32s() [4/6]
LlamaLibrary.Int32s.Int32s ()
Referenced by LlamaLibrary.Int32s.GetRange(), and LlamaLibrary.Int32s.Repeat().
Int32s() [5/6]
LlamaLibrary.Int32s.Int32s (Int32s other)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Int32s() [6/6]
LlamaLibrary.Int32s.Int32s (int capacity)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Member Function Documentation
Add()
void LlamaLibrary.Int32s.Add (int x)
References LlamaLibrary.libllama_libPINVOKE.Int32s_Add(), and LlamaLibrary.Int32s.swigCPtr.
Referenced by LlamaLibrary.Int32s.Int32s(), and LlamaLibrary.Int32s.Int32s().
AddRange()
void LlamaLibrary.Int32s.AddRange (Int32s values)
References LlamaLibrary.Int32s.getCPtr(), LlamaLibrary.libllama_libPINVOKE.Int32s_AddRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
capacity()
uint LlamaLibrary.Int32s.capacity () private
References LlamaLibrary.libllama_libPINVOKE.Int32s_capacity(), and LlamaLibrary.Int32s.swigCPtr.
Clear()
void LlamaLibrary.Int32s.Clear ()
References LlamaLibrary.libllama_libPINVOKE.Int32s_Clear(), and LlamaLibrary.Int32s.swigCPtr.
Contains()
bool LlamaLibrary.Int32s.Contains (int value)
References LlamaLibrary.libllama_libPINVOKE.Int32s_Contains(), and LlamaLibrary.Int32s.swigCPtr.
CopyTo() [1/3]
void LlamaLibrary.Int32s.CopyTo (int index, int[] array, int arrayIndex, int count)
References LlamaLibrary.Int32s.Count, and LlamaLibrary.Int32s.getitemcopy().
CopyTo() [2/3]
void LlamaLibrary.Int32s.CopyTo (int[] array)
References LlamaLibrary.Int32s.CopyTo(), and LlamaLibrary.Int32s.Count.
Referenced by LlamaLibrary.Int32s.CopyTo(), LlamaLibrary.Int32s.CopyTo(), and LlamaLibrary.Int32s.ToArray().
CopyTo() [3/3]
void LlamaLibrary.Int32s.CopyTo (int[] array, int arrayIndex)
References LlamaLibrary.Int32s.CopyTo(), and LlamaLibrary.Int32s.Count.
Dispose()
virtual void LlamaLibrary.Int32s.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_Int32s(), LlamaLibrary.Int32s.swigCMemOwn, and LlamaLibrary.Int32s.swigCPtr.
Referenced by LlamaLibrary.Int32s.~Int32s().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.Int32s.getCPtr (Int32s obj) static package
References LlamaLibrary.Int32s.swigCPtr.
Referenced by LlamaLibrary.Int32s.AddRange(), LlamaLibrary.Int32s.InsertRange(), and LlamaLibrary.Int32s.SetRange().
GetEnumerator() [1/3]
global.System.Collections.Generic.IEnumerator< int > global.System.Collections.Generic.IEnumerable< int >. LlamaLibrary.Int32s.GetEnumerator () private
GetEnumerator() [2/3]
global.System.Collections.IEnumerator global.System.Collections.IEnumerable. LlamaLibrary.Int32s.GetEnumerator () private
GetEnumerator() [3/3]
Int32sEnumerator LlamaLibrary.Int32s.GetEnumerator ()
getitem()
int LlamaLibrary.Int32s.getitem (int index) private
References LlamaLibrary.libllama_libPINVOKE.Int32s_getitem(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
getitemcopy()
int LlamaLibrary.Int32s.getitemcopy (int index) private
References LlamaLibrary.libllama_libPINVOKE.Int32s_getitemcopy(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
Referenced by LlamaLibrary.Int32s.CopyTo().
GetRange()
Int32s LlamaLibrary.Int32s.GetRange (int index, int count)
References LlamaLibrary.Int32s.Int32s(), LlamaLibrary.libllama_libPINVOKE.Int32s_GetRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
IndexOf()
int LlamaLibrary.Int32s.IndexOf (int value)
References LlamaLibrary.libllama_libPINVOKE.Int32s_IndexOf(), and LlamaLibrary.Int32s.swigCPtr.
Insert()
void LlamaLibrary.Int32s.Insert (int index, int x)
References LlamaLibrary.libllama_libPINVOKE.Int32s_Insert(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
InsertRange()
void LlamaLibrary.Int32s.InsertRange (int index, Int32s values)
References LlamaLibrary.Int32s.getCPtr(), LlamaLibrary.libllama_libPINVOKE.Int32s_InsertRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
LastIndexOf()
int LlamaLibrary.Int32s.LastIndexOf (int value)
References LlamaLibrary.libllama_libPINVOKE.Int32s_LastIndexOf(), and LlamaLibrary.Int32s.swigCPtr.
Remove()
bool LlamaLibrary.Int32s.Remove (int value)
References LlamaLibrary.libllama_libPINVOKE.Int32s_Remove(), and LlamaLibrary.Int32s.swigCPtr.
RemoveAt()
void LlamaLibrary.Int32s.RemoveAt (int index)
References LlamaLibrary.libllama_libPINVOKE.Int32s_RemoveAt(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
RemoveRange()
void LlamaLibrary.Int32s.RemoveRange (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.Int32s_RemoveRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
Repeat()
static Int32s LlamaLibrary.Int32s.Repeat (int value, int count) static
References LlamaLibrary.Int32s.Int32s(), LlamaLibrary.libllama_libPINVOKE.Int32s_Repeat(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
reserve()
void LlamaLibrary.Int32s.reserve (uint n) private
References LlamaLibrary.libllama_libPINVOKE.Int32s_reserve(), and LlamaLibrary.Int32s.swigCPtr.
Reverse() [1/2]
void LlamaLibrary.Int32s.Reverse ()
References LlamaLibrary.libllama_libPINVOKE.Int32s_Reverse__SWIG_0(), and LlamaLibrary.Int32s.swigCPtr.
Reverse() [2/2]
void LlamaLibrary.Int32s.Reverse (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.Int32s_Reverse__SWIG_1(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
setitem()
void LlamaLibrary.Int32s.setitem (int index, int value) private
References LlamaLibrary.libllama_libPINVOKE.Int32s_setitem(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
SetRange()
void LlamaLibrary.Int32s.SetRange (int index, Int32s values)
References LlamaLibrary.Int32s.getCPtr(), LlamaLibrary.libllama_libPINVOKE.Int32s_SetRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.Int32s.swigCPtr.
size()
uint LlamaLibrary.Int32s.size () private
References LlamaLibrary.libllama_libPINVOKE.Int32s_size(), and LlamaLibrary.Int32s.swigCPtr.
Referenced by LlamaLibrary.Int32s.Int32sEnumerator.MoveNext().
ToArray()
int[] LlamaLibrary.Int32s.ToArray ()
References LlamaLibrary.Int32s.CopyTo(), and LlamaLibrary.Int32s.Count.
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.Int32s.swigCMemOwn protected
Referenced by LlamaLibrary.Int32s.Dispose(), and LlamaLibrary.Int32s.Int32s().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.Int32s.swigCPtr private
Referenced by LlamaLibrary.Int32s.Add(), LlamaLibrary.Int32s.AddRange(), LlamaLibrary.Int32s.capacity(), LlamaLibrary.Int32s.Clear(), LlamaLibrary.Int32s.Contains(), LlamaLibrary.Int32s.Dispose(), LlamaLibrary.Int32s.getCPtr(), LlamaLibrary.Int32s.getitem(), LlamaLibrary.Int32s.getitemcopy(), LlamaLibrary.Int32s.GetRange(), LlamaLibrary.Int32s.IndexOf(), LlamaLibrary.Int32s.Insert(), LlamaLibrary.Int32s.InsertRange(), LlamaLibrary.Int32s.Int32s(), LlamaLibrary.Int32s.LastIndexOf(), LlamaLibrary.Int32s.Remove(), LlamaLibrary.Int32s.RemoveAt(), LlamaLibrary.Int32s.RemoveRange(), LlamaLibrary.Int32s.reserve(), LlamaLibrary.Int32s.Reverse(), LlamaLibrary.Int32s.Reverse(), LlamaLibrary.Int32s.setitem(), LlamaLibrary.Int32s.SetRange(), and LlamaLibrary.Int32s.size().
Property Documentation
Capacity
int LlamaLibrary.Int32s.Capacity get set
Count
int LlamaLibrary.Int32s.Count get
Referenced by LlamaLibrary.Int32s.CopyTo(), LlamaLibrary.Int32s.CopyTo(), LlamaLibrary.Int32s.CopyTo(), LlamaLibrary.Int32s.Int32sEnumerator.Int32sEnumerator(), LlamaLibrary.Int32s.Int32sEnumerator.MoveNext(), LlamaLibrary.Int32s.Int32sEnumerator.Reset(), and LlamaLibrary.Int32s.ToArray().
IsFixedSize
bool LlamaLibrary.Int32s.IsFixedSize get
IsReadOnly
bool LlamaLibrary.Int32s.IsReadOnly get
IsSynchronized
bool LlamaLibrary.Int32s.IsSynchronized get
this[int index]
int LlamaLibrary.Int32s.this[int index] get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/Int32s.cs