StyledLines from testedlines.com: C# docs: PrintGeneratedText Class Reference
PrintGeneratedText Class Reference
Public Attributes
RunModelAsync StateController
TMP_Text UiObject
Private Member Functions
void OnDestroy ()
void OnStateChanged (string text)
void Start ()
Member Function Documentation
OnDestroy()
void PrintGeneratedText.OnDestroy () private
References RunModelAsync.OnGeneratedComplete, RunModelAsync.OnGeneratedOutputChanged, OnStateChanged(), and StateController.
OnStateChanged()
void PrintGeneratedText.OnStateChanged (string text) private
Referenced by OnDestroy(), and Start().
Start()
void PrintGeneratedText.Start () private
References RunModelAsync.OnGeneratedComplete, RunModelAsync.OnGeneratedOutputChanged, OnStateChanged(), and StateController.
Member Data Documentation
StateController
RunModelAsync PrintGeneratedText.StateController
Referenced by OnDestroy(), and Start().
UiObject
TMP_Text PrintGeneratedText.UiObject
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/PrintGeneratedText.cs