StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.DialogUtils.DialogManager Class Reference
Assets.StyledLines.Runtime.DialogUtils.DialogManager Class Reference
Classes
class Character
Serializable class representing a character in the dialog system.
Public Member Functions
DialogManager (bool loop)
Constructor for initializing the DialogManager with a loop setting.
void ReparseDialogAndStyles ()
Re-parses the dialog and styles when the dialog text changes.
Public Attributes
BinaryAsset binaryFileAsset
The asset containing binary data used by the model controller.
List< Character > Characters = new()
List of characters involved in the dialog.
string EditorUiDialogText
Dialog text shown in the editor UI for easy modification.
UnityEvent< GameObject, string > OnCharacterSpeakEvent
UnityEvent< string > OnDialogUpdateEvent
Properties
string DialogText [get, set]
Property for accessing and modifying the dialog text. It also triggers re-parsing and events when modified.
Private Member Functions
void CreateTextMeshesIfMissing ()
Ensures that each character has a TextMeshPro component for displaying dialog, creating one if necessary.
Bounds GetCombinedBounds (GameObject characterObject)
Calculates the combined bounds of all renderers in a character's GameObject.
IEnumerator< WaitForSeconds > HideTextAfterDelay (TextMeshPro textMesh, float delay)
Coroutine that hides the text by clearing it after a specified delay.
void ParseDialog ()
Parses the dialog text into individual lines based on a specific format.
IEnumerator ShowNextLine ()
Coroutine that displays the next line of dialog, handles looping, and manages the dialog's progression.
void ShowText (GameObject characterObject, string text)
Displays the specified text on the character's TextMeshPro component.
void Start ()
Called when the script starts; initializes the model controller, parses the dialog, and starts the dialog sequence.
void StartDialog ()
Starts the dialog sequence, setting the initial index and activating the dialog.
void Update ()
Called every frame; updates dialog progression and rotates text objects to face the camera.
Private Attributes
int _currentDialogIndex
float _defaultTextMeshHeightAboveAabb = 0.5f
bool _isDialogActive
bool _isUpdatingDialogText = false
Flag to prevent recursive dialog updates.
ModelController _llmController = null
Reference to the model controller for generating dialog responses.
bool _loop
Camera _mainCamera
float _minResponseDelay = 1000f
List< string > _parsedDialog = new()
float _timer
float _timeToShowLine = 2000f
bool isLineDisplaying = false
Constructor & Destructor Documentation
DialogManager()
Assets.StyledLines.Runtime.DialogUtils.DialogManager.DialogManager (bool loop)
Constructor for initializing the DialogManager with a loop setting.
Parameters
loop
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._loop.
Member Function Documentation
CreateTextMeshesIfMissing()
void Assets.StyledLines.Runtime.DialogUtils.DialogManager.CreateTextMeshesIfMissing () private
Ensures that each character has a TextMeshPro component for displaying dialog, creating one if necessary.
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._defaultTextMeshHeightAboveAabb, Assets.StyledLines.Runtime.DialogUtils.DialogManager.Characters, and Assets.StyledLines.Runtime.DialogUtils.DialogManager.GetCombinedBounds().
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start().
GetCombinedBounds()
Bounds Assets.StyledLines.Runtime.DialogUtils.DialogManager.GetCombinedBounds (GameObject characterObject) private
Calculates the combined bounds of all renderers in a character's GameObject.
Parameters
characterObject
Returns
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.CreateTextMeshesIfMissing().
HideTextAfterDelay()
IEnumerator< WaitForSeconds > Assets.StyledLines.Runtime.DialogUtils.DialogManager.HideTextAfterDelay (TextMeshPro textMesh, float delay) private
Coroutine that hides the text by clearing it after a specified delay.
Parameters
textMesh
delay
Returns
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowText().
ParseDialog()
void Assets.StyledLines.Runtime.DialogUtils.DialogManager.ParseDialog () private
Parses the dialog text into individual lines based on a specific format.
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._parsedDialog, and Assets.StyledLines.Runtime.DialogUtils.DialogManager.DialogText.
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ReparseDialogAndStyles(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start().
ReparseDialogAndStyles()
void Assets.StyledLines.Runtime.DialogUtils.DialogManager.ReparseDialogAndStyles ()
Re-parses the dialog and styles when the dialog text changes.
References Assets.StyledLines.Runtime.DialogUtils.DialogManager.ParseDialog().
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogTextAndCharacterStylesResetter.ResetStylesAndDialog().
ShowNextLine()
IEnumerator Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine () private
Coroutine that displays the next line of dialog, handles looping, and manages the dialog's progression.
Returns
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._currentDialogIndex, Assets.StyledLines.Runtime.DialogUtils.DialogManager._isDialogActive, Assets.StyledLines.Runtime.DialogUtils.DialogManager._llmController, Assets.StyledLines.Runtime.DialogUtils.DialogManager._loop, Assets.StyledLines.Runtime.DialogUtils.DialogManager._parsedDialog, Assets.StyledLines.Runtime.DialogUtils.DialogManager.Characters, Assets.StyledLines.Runtime.LlamaInfrenceUnity.ModelController.ExtractFirstPart(), Assets.StyledLines.Runtime.DialogUtils.DialogManager.isLineDisplaying, Assets.StyledLines.Runtime.LlamaInfrenceUnity.ModelController.model, Assets.StyledLines.Runtime.DialogUtils.DialogManager.OnCharacterSpeakEvent, and Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowText().
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.StartDialog(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
ShowText()
void Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowText (GameObject characterObject, string text) private
Displays the specified text on the character's TextMeshPro component.
Parameters
characterObject
text
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._timeToShowLine, and Assets.StyledLines.Runtime.DialogUtils.DialogManager.HideTextAfterDelay().
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine().
Start()
void Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start () private
Called when the script starts; initializes the model controller, parses the dialog, and starts the dialog sequence.
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._llmController, Assets.StyledLines.Runtime.DialogUtils.DialogManager._mainCamera, Assets.StyledLines.Runtime.DialogUtils.DialogManager._parsedDialog, Assets.StyledLines.Runtime.DialogUtils.DialogManager.binaryFileAsset, Assets.StyledLines.Runtime.DialogUtils.DialogManager.CreateTextMeshesIfMissing(), Assets.StyledLines.Runtime.DialogUtils.DialogManager.DialogText, Assets.StyledLines.Runtime.DialogUtils.DialogManager.EditorUiDialogText, Assets.StyledLines.Runtime.DialogUtils.DialogManager.ParseDialog(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.StartDialog().
StartDialog()
void Assets.StyledLines.Runtime.DialogUtils.DialogManager.StartDialog () private
Starts the dialog sequence, setting the initial index and activating the dialog.
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._currentDialogIndex, Assets.StyledLines.Runtime.DialogUtils.DialogManager._isDialogActive, and Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine().
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start().
Update()
void Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update () private
Called every frame; updates dialog progression and rotates text objects to face the camera.
References Assets.StyledLines.Runtime.DialogUtils.DialogManager._isDialogActive, Assets.StyledLines.Runtime.DialogUtils.DialogManager._mainCamera, Assets.StyledLines.Runtime.DialogUtils.DialogManager._minResponseDelay, Assets.StyledLines.Runtime.DialogUtils.DialogManager._timer, Assets.StyledLines.Runtime.DialogUtils.DialogManager._timeToShowLine, Assets.StyledLines.Runtime.DialogUtils.DialogManager.Characters, Assets.StyledLines.Runtime.DialogUtils.DialogManager.isLineDisplaying, and Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine().
Member Data Documentation
_currentDialogIndex
int Assets.StyledLines.Runtime.DialogUtils.DialogManager._currentDialogIndex private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.StartDialog().
_defaultTextMeshHeightAboveAabb
float Assets.StyledLines.Runtime.DialogUtils.DialogManager._defaultTextMeshHeightAboveAabb = 0.5f private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.CreateTextMeshesIfMissing().
_isDialogActive
bool Assets.StyledLines.Runtime.DialogUtils.DialogManager._isDialogActive private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine(), Assets.StyledLines.Runtime.DialogUtils.DialogManager.StartDialog(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
_isUpdatingDialogText
bool Assets.StyledLines.Runtime.DialogUtils.DialogManager._isUpdatingDialogText = false private
Flag to prevent recursive dialog updates.
_llmController
ModelController Assets.StyledLines.Runtime.DialogUtils.DialogManager._llmController = null private
Reference to the model controller for generating dialog responses.
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start().
_loop
bool Assets.StyledLines.Runtime.DialogUtils.DialogManager._loop private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.DialogManager(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine().
_mainCamera
Camera Assets.StyledLines.Runtime.DialogUtils.DialogManager._mainCamera private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
_minResponseDelay
float Assets.StyledLines.Runtime.DialogUtils.DialogManager._minResponseDelay = 1000f private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
_parsedDialog
List<string> Assets.StyledLines.Runtime.DialogUtils.DialogManager._parsedDialog = new() private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ParseDialog(), Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start().
_timer
float Assets.StyledLines.Runtime.DialogUtils.DialogManager._timer private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
_timeToShowLine
float Assets.StyledLines.Runtime.DialogUtils.DialogManager._timeToShowLine = 2000f private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowText(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
binaryFileAsset
BinaryAsset Assets.StyledLines.Runtime.DialogUtils.DialogManager.binaryFileAsset
The asset containing binary data used by the model controller.
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start().
Characters
List<Character> Assets.StyledLines.Runtime.DialogUtils.DialogManager.Characters = new()
List of characters involved in the dialog.
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.CreateTextMeshesIfMissing(), Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnCharacterSelected(), Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnStyleChanged(), Assets.StyledLines.Runtime.DialogUtils.DialogTextAndCharacterStylesResetter.ResetStylesAndDialog(), Assets.StyledLines.Runtime.DialogUtils.DialogTextAndCharacterStylesResetter.SaveInitialState(), Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine(), Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
EditorUiDialogText
string Assets.StyledLines.Runtime.DialogUtils.DialogManager.EditorUiDialogText
Dialog text shown in the editor UI for easy modification.
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start().
isLineDisplaying
bool Assets.StyledLines.Runtime.DialogUtils.DialogManager.isLineDisplaying = false private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.Update().
OnCharacterSpeakEvent
UnityEvent<GameObject, string> Assets.StyledLines.Runtime.DialogUtils.DialogManager.OnCharacterSpeakEvent
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ShowNextLine().
OnDialogUpdateEvent
UnityEvent<string> Assets.StyledLines.Runtime.DialogUtils.DialogManager.OnDialogUpdateEvent
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.Start().
Property Documentation
DialogText
string Assets.StyledLines.Runtime.DialogUtils.DialogManager.DialogText get set
Property for accessing and modifying the dialog text. It also triggers re-parsing and events when modified.
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogManager.ParseDialog(), Assets.StyledLines.Runtime.DialogUtils.DialogTextAndCharacterStylesResetter.SaveInitialState(), Assets.StyledLines.Runtime.DialogUtils.DialogManager.Start(), and Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/DialogUtils/DialogManager.cs