StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample Class Reference
Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample Class Reference
Public Attributes
BinaryAsset binaryFileAsset
Public variable to hold a reference to the binary asset containing the model's data.
Private Member Functions
IEnumerator GenerateLine ()
Coroutine to handle the asynchronous generation of text from the language model. Coroutines allow the function to pause execution and resume later, making it perfect for waiting on asynchronous operations.
void Start ()
The Start method is called when the script instance is being loaded. It initializes the ModelController with the binary file asset and starts the generation process.
Private Attributes
ModelController _llmController = null
Private variable to hold an instance of the ModelController class. This controller will manage the interaction with the language model.
Member Function Documentation
GenerateLine()
IEnumerator Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.GenerateLine () private
Coroutine to handle the asynchronous generation of text from the language model. Coroutines allow the function to pause execution and resume later, making it perfect for waiting on asynchronous operations.
Returns
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample._llmController, Assets.StyledLines.Runtime.LlamaInfrenceUnity.ModelController.ExtractFirstPart(), and Assets.StyledLines.Runtime.LlamaInfrenceUnity.ModelController.model.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.Start().
Start()
void Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.Start () private
The Start method is called when the script instance is being loaded. It initializes the ModelController with the binary file asset and starts the generation process.
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample._llmController, Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.binaryFileAsset, and Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.GenerateLine().
Member Data Documentation
_llmController
ModelController Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample._llmController = null private
Private variable to hold an instance of the ModelController class. This controller will manage the interaction with the language model.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.GenerateLine(), and Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.Start().
binaryFileAsset
BinaryAsset Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.binaryFileAsset
Public variable to hold a reference to the binary asset containing the model's data.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.MinimalExample.Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrenceUnity/MinimalExample.cs