StyledLines from testedlines.com: C# docs: LlamaLibrary.LlamaInfrence Class Reference
LlamaLibrary.LlamaInfrence Class Reference
Public Member Functions
virtual void Dispose ()
void Echo (string arg0)
bool Generate (string prompt)
string GetGenerated ()
LlamaInfrence (global::System.IntPtr cPtr, bool cMemoryOwn)
LlamaInfrence (LoggingContext logging, gpt_params cfg_params)
void Stop ()
Static Public Member Functions
static gpt_params GetParameters (string llamacpp_cmd_args)
Protected Attributes
bool swigCMemOwn
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (LlamaInfrence obj)
Properties
SWIGTYPE_p_LlamaInfrence__LlamaImpl pImpl [get, set]
Private Member Functions
~LlamaInfrence ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
LlamaInfrence() [1/2]
LlamaLibrary.LlamaInfrence.LlamaInfrence (global::System::IntPtr cPtr, bool cMemoryOwn)
References LlamaLibrary.LlamaInfrence.swigCMemOwn, and LlamaLibrary.LlamaInfrence.swigCPtr.
~LlamaInfrence()
LlamaLibrary.LlamaInfrence.~LlamaInfrence () private
References LlamaLibrary.LlamaInfrence.Dispose().
LlamaInfrence() [2/2]
LlamaLibrary.LlamaInfrence.LlamaInfrence (LoggingContext logging, gpt_params cfg_params)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Member Function Documentation
Dispose()
virtual void LlamaLibrary.LlamaInfrence.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_LlamaInfrence(), LlamaLibrary.LlamaInfrence.swigCMemOwn, and LlamaLibrary.LlamaInfrence.swigCPtr.
Referenced by LlamaLibrary.LlamaInfrence.~LlamaInfrence().
Echo()
void LlamaLibrary.LlamaInfrence.Echo (string arg0)
References LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_Echo(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaInfrence.swigCPtr.
Generate()
bool LlamaLibrary.LlamaInfrence.Generate (string prompt)
References LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_Generate(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaInfrence.swigCPtr.
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.LlamaInfrence.getCPtr (LlamaInfrence obj) static package
References LlamaLibrary.LlamaInfrence.swigCPtr.
GetGenerated()
string LlamaLibrary.LlamaInfrence.GetGenerated ()
References LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_GetGenerated(), and LlamaLibrary.LlamaInfrence.swigCPtr.
GetParameters()
static gpt_params LlamaLibrary.LlamaInfrence.GetParameters (string llamacpp_cmd_args) static
References LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_GetParameters(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Stop()
void LlamaLibrary.LlamaInfrence.Stop ()
References LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_Stop(), and LlamaLibrary.LlamaInfrence.swigCPtr.
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.LlamaInfrence.swigCMemOwn protected
Referenced by LlamaLibrary.LlamaInfrence.Dispose(), and LlamaLibrary.LlamaInfrence.LlamaInfrence().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.LlamaInfrence.swigCPtr private
Referenced by LlamaLibrary.LlamaInfrence.Dispose(), LlamaLibrary.LlamaInfrence.Echo(), LlamaLibrary.LlamaInfrence.Generate(), LlamaLibrary.LlamaInfrence.getCPtr(), LlamaLibrary.LlamaInfrence.GetGenerated(), LlamaLibrary.LlamaInfrence.LlamaInfrence(), and LlamaLibrary.LlamaInfrence.Stop().
Property Documentation
pImpl
SWIGTYPE_p_LlamaInfrence__LlamaImpl LlamaLibrary.LlamaInfrence.pImpl get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/LlamaInfrence.cs