StyledLines from testedlines.com: C# docs: LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info Class Reference
LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info Class Reference
Protected Member Functions
SWIGTYPE_p_llama_control_vector_load_info ()
Package Functions
SWIGTYPE_p_llama_control_vector_load_info (global::System.IntPtr cPtr, bool futureUse)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (SWIGTYPE_p_llama_control_vector_load_info obj)
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
SWIGTYPE_p_llama_control_vector_load_info() [1/2]
LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.SWIGTYPE_p_llama_control_vector_load_info (global::System::IntPtr cPtr, bool futureUse) package
References LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.swigCPtr.
SWIGTYPE_p_llama_control_vector_load_info() [2/2]
LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.SWIGTYPE_p_llama_control_vector_load_info () protected
References LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.swigCPtr.
Member Function Documentation
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.getCPtr (SWIGTYPE_p_llama_control_vector_load_info obj) static package
References LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.swigCPtr.
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Add(), LlamaLibrary.LlamaControlVectorLoadInfos.Insert(), LlamaLibrary.LlamaControlVectorLoadInfos.Repeat(), and LlamaLibrary.LlamaControlVectorLoadInfos.setitem().
Member Data Documentation
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.swigCPtr private
Referenced by LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.getCPtr(), LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.SWIGTYPE_p_llama_control_vector_load_info(), and LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.SWIGTYPE_p_llama_control_vector_load_info().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/SWIGTYPE_p_llama_control_vector_load_info.cs