StyledLines from testedlines.com: C# docs: LogToUI Class Reference
LogToUI Class Reference
Public Attributes
TMP_Text logText
Private Member Functions
void HandleLog (string logString, string stackTrace, LogType type)
void OnDisable ()
void OnEnable ()
Private Attributes
StringBuilder logBuilder = new StringBuilder()
Member Function Documentation
HandleLog()
void LogToUI.HandleLog (string logString, string stackTrace, LogType type) private
References logBuilder.
Referenced by OnDisable(), and OnEnable().
OnDisable()
void LogToUI.OnDisable () private
References HandleLog().
OnEnable()
void LogToUI.OnEnable () private
References HandleLog().
Member Data Documentation
logBuilder
StringBuilder LogToUI.logBuilder = new StringBuilder() private
Referenced by HandleLog().
logText
TMP_Text LogToUI.logText
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/LogToUI.cs