StyledLines from testedlines.com: C# docs: DialogTextMapper Class Reference
DialogTextMapper Class Reference
Private Member Functions
void OnDialogTextChanged (string newDialogText)
void OnDialogTextExternalUpdate (string newDialogText)
void Start ()
Private Attributes
TMP_InputField dialogInputField
DialogManager dialogManager
Member Function Documentation
OnDialogTextChanged()
void DialogTextMapper.OnDialogTextChanged (string newDialogText) private
References dialogManager.
Referenced by Start().
OnDialogTextExternalUpdate()
void DialogTextMapper.OnDialogTextExternalUpdate (string newDialogText) private
Referenced by Start().
Start()
void DialogTextMapper.Start () private
References dialogInputField, dialogManager, DialogManager.DialogText, OnDialogTextChanged(), OnDialogTextExternalUpdate(), and DialogManager.OnDialogUpdateEvent.
Member Data Documentation
dialogInputField
TMP_InputField DialogTextMapper.dialogInputField private
Referenced by Start().
dialogManager
DialogManager DialogTextMapper.dialogManager private
Referenced by OnDialogTextChanged(), and Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/DialogUtils/DialogTextMapper.cs