StyledLines from testedlines.com: C# docs: LlamaLibrary.libllama_libPINVOKE Class Reference
LlamaLibrary.libllama_libPINVOKE Class Reference
Classes
class MonoPInvokeCallbackAttribute
class SWIGExceptionHelper
class SWIGPendingException
class SWIGStringHelper
Public Member Functions
static void AsyncLlamaInfrence_ClearAllTasks (global::System.Runtime.InteropServices.HandleRef jarg1)
static int AsyncLlamaInfrence_GenerateAsync (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string AsyncLlamaInfrence_GetGenerationResults (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool AsyncLlamaInfrence_GetSetupResults (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool AsyncLlamaInfrence_IsGenerationReady (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr AsyncLlamaInfrence_pImpl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void AsyncLlamaInfrence_pImpl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static int AsyncLlamaInfrence_SetupAsync (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static int cpu_get_num_math ()
static int cpu_get_num_physical_cores ()
static void delete_AsyncLlamaInfrence (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_FileWrapper (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_gpt_params (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_Int32s (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_llama_sampling_params (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_LlamaControlVectorLoadInfos (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_LlamaInfrence (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_LoggingContext (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_StringAndFloat (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_Strings (global::System.Runtime.InteropServices.HandleRef jarg1)
static void delete_StringsAndFloats (global::System.Runtime.InteropServices.HandleRef jarg1)
static bool FileWrapper_Save__SWIG_0 (string jarg1, string jarg2)
static bool FileWrapper_Save__SWIG_1 ([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, string jarg3)
static bool FileWrapper_Save__SWIG_2 (string jarg1, uint jarg2, string jarg3)
static global::System.IntPtr gpt_params_antiprompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_antiprompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static global::System.IntPtr gpt_params_api_keys_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_api_keys_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static int gpt_params_attention_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_attention_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static string gpt_params_cache_type_k_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cache_type_k_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_cache_type_v_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cache_type_v_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static global::System.IntPtr gpt_params_cb_eval_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cb_eval_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static global::System.IntPtr gpt_params_cb_eval_user_data_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cb_eval_user_data_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static string gpt_params_chat_template_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_chat_template_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static bool gpt_params_check_tensors_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_check_tensors_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static string gpt_params_chunk_separator_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_chunk_separator_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static int gpt_params_chunk_size_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_chunk_size_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_compute_ppl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_compute_ppl_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_cont_batching_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cont_batching_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static global::System.IntPtr gpt_params_context_files_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_context_files_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static int gpt_params_control_vector_layer_end_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_control_vector_layer_end_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_control_vector_layer_start_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_control_vector_layer_start_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr gpt_params_control_vectors_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_control_vectors_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static bool gpt_params_conversation_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_conversation_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static int gpt_params_cvector_dimre_method_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cvector_dimre_method_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static string gpt_params_cvector_negative_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cvector_negative_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_cvector_outfile_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cvector_outfile_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_cvector_positive_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_cvector_positive_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static float gpt_params_defrag_thold_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_defrag_thold_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static bool gpt_params_display_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_display_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_dump_kv_cache_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_dump_kv_cache_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static int gpt_params_embd_normalize_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_embd_normalize_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static string gpt_params_embd_out_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_embd_out_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_embd_sep_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_embd_sep_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static bool gpt_params_embedding_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_embedding_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_enable_chat_template_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_enable_chat_template_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_endpoint_metrics_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_endpoint_metrics_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_endpoint_slots_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_endpoint_slots_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_escape_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_escape_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_flash_attn_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_flash_attn_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static int gpt_params_grp_attn_n_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_grp_attn_n_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_grp_attn_w_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_grp_attn_w_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_hellaswag_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_hellaswag_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static uint gpt_params_hellaswag_tasks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_hellaswag_tasks_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static string gpt_params_hf_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_hf_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_hf_repo_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_hf_repo_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_hf_token_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_hf_token_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_hostname_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_hostname_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static int gpt_params_i_chunk_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_i_chunk_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_i_pos_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_i_pos_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_ignore_eos_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_ignore_eos_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static global::System.IntPtr gpt_params_image_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_image_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static global::System.IntPtr gpt_params_in_files_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_in_files_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static bool gpt_params_infill_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_infill_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_input_prefix_bos_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_input_prefix_bos_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static string gpt_params_input_prefix_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_input_prefix_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_input_suffix_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_input_suffix_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static bool gpt_params_interactive_first_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_interactive_first_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_interactive_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_interactive_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_is_pp_shared_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_is_pp_shared_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_kl_divergence_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_kl_divergence_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static global::System.IntPtr gpt_params_kv_overrides_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_kv_overrides_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static bool gpt_params_log_json_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_log_json_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static string gpt_params_logdir_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_logdir_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static bool gpt_params_logits_all_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_logits_all_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static string gpt_params_logits_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_logits_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_lookup_cache_dynamic_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_lookup_cache_dynamic_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_lookup_cache_static_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_lookup_cache_static_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static global::System.IntPtr gpt_params_lora_adapter_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_lora_adapter_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static string gpt_params_lora_outfile_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_lora_outfile_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static int gpt_params_main_gpu_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_main_gpu_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static string gpt_params_mmproj_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_mmproj_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_model_alias_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_model_alias_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_model_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_model_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_model_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_model_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_model_url_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_model_url_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static bool gpt_params_multiline_input_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_multiline_input_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_multiple_choice_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_multiple_choice_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static uint gpt_params_multiple_choice_tasks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_multiple_choice_tasks_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static int gpt_params_n_batch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_batch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_chunks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_chunks_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_ctx_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_ctx_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_gpu_layers_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_gpu_layers_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_gpu_layers_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_gpu_layers_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_junk_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_junk_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_keep_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_keep_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_out_freq_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_out_freq_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_parallel_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_parallel_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_pca_batch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_pca_batch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_pca_iterations_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_pca_iterations_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr gpt_params_n_pl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_pl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static global::System.IntPtr gpt_params_n_pp_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_pp_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static int gpt_params_n_predict_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_predict_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_print_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_print_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_save_freq_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_save_freq_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_sequences_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_sequences_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr gpt_params_n_tg_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_tg_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static int gpt_params_n_threads_batch_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_threads_batch_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_threads_batch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_threads_batch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_threads_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_threads_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_threads_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static int gpt_params_n_threads_http_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_threads_http_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void gpt_params_n_threads_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_n_ubatch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_n_ubatch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_no_kv_offload_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_no_kv_offload_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static global::System.IntPtr gpt_params_numa_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_numa_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static string gpt_params_out_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_out_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static float gpt_params_p_split_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_p_split_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static string gpt_params_path_prompt_cache_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_path_prompt_cache_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static int gpt_params_pooling_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_pooling_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_port_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_port_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_ppl_output_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_ppl_output_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_ppl_stride_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_ppl_stride_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_process_output_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_process_output_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_prompt_cache_all_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_prompt_cache_all_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_prompt_cache_ro_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_prompt_cache_ro_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static string gpt_params_prompt_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_prompt_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_public_path_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_public_path_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static float gpt_params_rope_freq_base_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_rope_freq_base_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float gpt_params_rope_freq_scale_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_rope_freq_scale_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static int gpt_params_rope_scaling_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_rope_scaling_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static string gpt_params_rpc_servers_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_rpc_servers_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static uint gpt_params_seed_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_seed_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static bool gpt_params_simple_io_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_simple_io_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static float gpt_params_slot_prompt_similarity_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_slot_prompt_similarity_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static string gpt_params_slot_save_path_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_slot_save_path_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static global::System.IntPtr gpt_params_sparams_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_sparams_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static bool gpt_params_special_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_special_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static int gpt_params_split_mode_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_split_mode_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_spm_infill_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_spm_infill_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static string gpt_params_ssl_file_cert_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_ssl_file_cert_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_ssl_file_key_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_ssl_file_key_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string gpt_params_system_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_system_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static global::System.IntPtr gpt_params_tensor_split_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_tensor_split_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static int gpt_params_timeout_read_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_timeout_read_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int gpt_params_timeout_write_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_timeout_write_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_usage_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_usage_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_use_color_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_use_color_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_use_mlock_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_use_mlock_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_use_mmap_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_use_mmap_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_verbose_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_verbose_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static int gpt_params_verbosity_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_verbosity_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool gpt_params_warmup_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_warmup_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static bool gpt_params_winogrande_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_winogrande_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static uint gpt_params_winogrande_tasks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_winogrande_tasks_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static float gpt_params_yarn_attn_factor_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_yarn_attn_factor_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float gpt_params_yarn_beta_fast_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_yarn_beta_fast_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float gpt_params_yarn_beta_slow_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_yarn_beta_slow_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float gpt_params_yarn_ext_factor_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_yarn_ext_factor_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static int gpt_params_yarn_orig_ctx_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void gpt_params_yarn_orig_ctx_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void Int32s_Add (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void Int32s_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static uint Int32s_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
static void Int32s_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
static bool Int32s_Contains (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int Int32s_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int Int32s_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr Int32s_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static int Int32s_IndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void Int32s_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void Int32s_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static int Int32s_LastIndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool Int32s_Remove (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void Int32s_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void Int32s_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static global::System.IntPtr Int32s_Repeat (int jarg1, int jarg2)
static void Int32s_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static void Int32s_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
static void Int32s_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void Int32s_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void Int32s_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static uint Int32s_size (global::System.Runtime.InteropServices.HandleRef jarg1)
static string llama_sampling_params_cfg_negative_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_cfg_negative_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static float llama_sampling_params_cfg_scale_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_cfg_scale_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float llama_sampling_params_dynatemp_exponent_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_dynatemp_exponent_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float llama_sampling_params_dynatemp_range_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_dynatemp_range_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static string llama_sampling_params_grammar_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_grammar_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static global::System.IntPtr llama_sampling_params_logit_bias_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_logit_bias_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static int llama_sampling_params_min_keep_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_min_keep_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static float llama_sampling_params_min_p_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_min_p_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float llama_sampling_params_mirostat_eta_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_mirostat_eta_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static int llama_sampling_params_mirostat_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_mirostat_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static float llama_sampling_params_mirostat_tau_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_mirostat_tau_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static int llama_sampling_params_n_prev_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_n_prev_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static int llama_sampling_params_n_probs_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_n_probs_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static bool llama_sampling_params_penalize_nl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_penalize_nl_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static float llama_sampling_params_penalty_freq_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_penalty_freq_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static int llama_sampling_params_penalty_last_n_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_penalty_last_n_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static float llama_sampling_params_penalty_present_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_penalty_present_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static global::System.IntPtr llama_sampling_params_penalty_prompt_tokens_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_penalty_prompt_tokens_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static float llama_sampling_params_penalty_repeat_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_penalty_repeat_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static global::System.IntPtr llama_sampling_params_samplers_sequence_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_samplers_sequence_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static uint llama_sampling_params_seed_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_seed_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static float llama_sampling_params_temp_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_temp_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float llama_sampling_params_tfs_z_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_tfs_z_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static int llama_sampling_params_top_k_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_top_k_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static float llama_sampling_params_top_p_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_top_p_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static float llama_sampling_params_typical_p_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_typical_p_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static bool llama_sampling_params_use_penalty_prompt_tokens_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void llama_sampling_params_use_penalty_prompt_tokens_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
static void LlamaControlVectorLoadInfos_Add (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static void LlamaControlVectorLoadInfos_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static uint LlamaControlVectorLoadInfos_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
static void LlamaControlVectorLoadInfos_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr LlamaControlVectorLoadInfos_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr LlamaControlVectorLoadInfos_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr LlamaControlVectorLoadInfos_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void LlamaControlVectorLoadInfos_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static void LlamaControlVectorLoadInfos_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static void LlamaControlVectorLoadInfos_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void LlamaControlVectorLoadInfos_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static global::System.IntPtr LlamaControlVectorLoadInfos_Repeat (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void LlamaControlVectorLoadInfos_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static void LlamaControlVectorLoadInfos_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
static void LlamaControlVectorLoadInfos_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void LlamaControlVectorLoadInfos_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static void LlamaControlVectorLoadInfos_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static uint LlamaControlVectorLoadInfos_size (global::System.Runtime.InteropServices.HandleRef jarg1)
static void LlamaInfrence_Echo (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static bool LlamaInfrence_Generate (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string LlamaInfrence_GetGenerated (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr LlamaInfrence_GetParameters (string jarg1)
static global::System.IntPtr LlamaInfrence_pImpl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void LlamaInfrence_pImpl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static void LlamaInfrence_Stop (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr LoggingContext_pImpl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void LoggingContext_pImpl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static global::System.IntPtr new_AsyncLlamaInfrence ()
static global::System.IntPtr new_FileWrapper ()
static global::System.IntPtr new_gpt_params ()
static global::System.IntPtr new_Int32s__SWIG_0 ()
static global::System.IntPtr new_Int32s__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr new_Int32s__SWIG_2 (int jarg1)
static global::System.IntPtr new_llama_sampling_params ()
static global::System.IntPtr new_LlamaControlVectorLoadInfos__SWIG_0 ()
static global::System.IntPtr new_LlamaControlVectorLoadInfos__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr new_LlamaControlVectorLoadInfos__SWIG_2 (int jarg1)
static global::System.IntPtr new_LlamaInfrence (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static global::System.IntPtr new_LoggingContext ()
static global::System.IntPtr new_StringAndFloat__SWIG_0 ()
static global::System.IntPtr new_StringAndFloat__SWIG_1 (string jarg1, float jarg2)
static global::System.IntPtr new_StringAndFloat__SWIG_2 (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr new_Strings__SWIG_0 ()
static global::System.IntPtr new_Strings__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr new_Strings__SWIG_2 (int jarg1)
static global::System.IntPtr new_StringsAndFloats__SWIG_0 ()
static global::System.IntPtr new_StringsAndFloats__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr new_StringsAndFloats__SWIG_2 (int jarg1)
static string StringAndFloat_first_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void StringAndFloat_first_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static float StringAndFloat_second_get (global::System.Runtime.InteropServices.HandleRef jarg1)
static void StringAndFloat_second_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
static void Strings_Add (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static void Strings_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static uint Strings_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
static void Strings_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
static bool Strings_Contains (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static string Strings_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static string Strings_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr Strings_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static int Strings_IndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static void Strings_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3)
static void Strings_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static int Strings_LastIndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static bool Strings_Remove (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
static void Strings_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void Strings_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static global::System.IntPtr Strings_Repeat (string jarg1, int jarg2)
static void Strings_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static void Strings_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
static void Strings_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void Strings_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3)
static void Strings_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static uint Strings_size (global::System.Runtime.InteropServices.HandleRef jarg1)
static void StringsAndFloats_Add (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static void StringsAndFloats_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
static uint StringsAndFloats_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
static void StringsAndFloats_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
static global::System.IntPtr StringsAndFloats_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr StringsAndFloats_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static global::System.IntPtr StringsAndFloats_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void StringsAndFloats_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static void StringsAndFloats_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static void StringsAndFloats_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void StringsAndFloats_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static global::System.IntPtr StringsAndFloats_Repeat (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
static void StringsAndFloats_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
static void StringsAndFloats_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
static void StringsAndFloats_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
static void StringsAndFloats_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static void StringsAndFloats_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
static uint StringsAndFloats_size (global::System.Runtime.InteropServices.HandleRef jarg1)
Static Public Attributes
const string LIBRARY_NAME = "libllama_lib"
Static Protected Attributes
static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper()
static SWIGStringHelper swigStringHelper = new SWIGStringHelper()
Static Private Member Functions
static libllama_libPINVOKE ()
Constructor & Destructor Documentation
libllama_libPINVOKE()
static LlamaLibrary.libllama_libPINVOKE.libllama_libPINVOKE () static private
Member Function Documentation
AsyncLlamaInfrence_ClearAllTasks()
static void LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_ClearAllTasks (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.AsyncLlamaInfrence.ClearAllTasks().
AsyncLlamaInfrence_GenerateAsync()
static int LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_GenerateAsync (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.AsyncLlamaInfrence.GenerateAsync().
AsyncLlamaInfrence_GetGenerationResults()
static string LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_GetGenerationResults (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.AsyncLlamaInfrence.GetGenerationResults().
AsyncLlamaInfrence_GetSetupResults()
static bool LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_GetSetupResults (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.AsyncLlamaInfrence.GetSetupResults().
AsyncLlamaInfrence_IsGenerationReady()
static bool LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_IsGenerationReady (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.AsyncLlamaInfrence.IsGenerationReady().
AsyncLlamaInfrence_pImpl_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_pImpl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
AsyncLlamaInfrence_pImpl_set()
static void LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_pImpl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
AsyncLlamaInfrence_SetupAsync()
static int LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_SetupAsync (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.AsyncLlamaInfrence.SetupAsync().
cpu_get_num_math()
static int LlamaLibrary.libllama_libPINVOKE.cpu_get_num_math ()
Referenced by LlamaLibrary.libllama_lib.cpu_get_num_math().
cpu_get_num_physical_cores()
static int LlamaLibrary.libllama_libPINVOKE.cpu_get_num_physical_cores ()
Referenced by LlamaLibrary.libllama_lib.cpu_get_num_physical_cores().
delete_AsyncLlamaInfrence()
static void LlamaLibrary.libllama_libPINVOKE.delete_AsyncLlamaInfrence (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.AsyncLlamaInfrence.Dispose().
delete_FileWrapper()
static void LlamaLibrary.libllama_libPINVOKE.delete_FileWrapper (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.FileWrapper.Dispose().
delete_gpt_params()
static void LlamaLibrary.libllama_libPINVOKE.delete_gpt_params (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.gpt_params.Dispose().
delete_Int32s()
static void LlamaLibrary.libllama_libPINVOKE.delete_Int32s (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Int32s.Dispose().
delete_llama_sampling_params()
static void LlamaLibrary.libllama_libPINVOKE.delete_llama_sampling_params (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.llama_sampling_params.Dispose().
delete_LlamaControlVectorLoadInfos()
static void LlamaLibrary.libllama_libPINVOKE.delete_LlamaControlVectorLoadInfos (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Dispose().
delete_LlamaInfrence()
static void LlamaLibrary.libllama_libPINVOKE.delete_LlamaInfrence (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaInfrence.Dispose().
delete_LoggingContext()
static void LlamaLibrary.libllama_libPINVOKE.delete_LoggingContext (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LoggingContext.Dispose().
delete_StringAndFloat()
static void LlamaLibrary.libllama_libPINVOKE.delete_StringAndFloat (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.StringAndFloat.Dispose().
delete_Strings()
static void LlamaLibrary.libllama_libPINVOKE.delete_Strings (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Strings.Dispose().
delete_StringsAndFloats()
static void LlamaLibrary.libllama_libPINVOKE.delete_StringsAndFloats (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.StringsAndFloats.Dispose().
FileWrapper_Save__SWIG_0()
static bool LlamaLibrary.libllama_libPINVOKE.FileWrapper_Save__SWIG_0 (string jarg1, string jarg2)
Referenced by LlamaLibrary.FileWrapper.Save().
FileWrapper_Save__SWIG_1()
static bool LlamaLibrary.libllama_libPINVOKE.FileWrapper_Save__SWIG_1 ([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)] byte[] jarg1, int jarg2, string jarg3)
Referenced by LlamaLibrary.FileWrapper.Save().
FileWrapper_Save__SWIG_2()
static bool LlamaLibrary.libllama_libPINVOKE.FileWrapper_Save__SWIG_2 (string jarg1, uint jarg2, string jarg3)
Referenced by LlamaLibrary.FileWrapper.Save().
gpt_params_antiprompt_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_antiprompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_antiprompt_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_antiprompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_api_keys_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_api_keys_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_api_keys_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_api_keys_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_attention_type_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_attention_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_attention_type_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_attention_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_cache_type_k_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_cache_type_k_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cache_type_k_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cache_type_k_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_cache_type_v_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_cache_type_v_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cache_type_v_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cache_type_v_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_cb_eval_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_cb_eval_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cb_eval_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cb_eval_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_cb_eval_user_data_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_cb_eval_user_data_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cb_eval_user_data_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cb_eval_user_data_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_chat_template_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_chat_template_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_chat_template_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_chat_template_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_check_tensors_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_check_tensors_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_check_tensors_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_check_tensors_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_chunk_separator_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_chunk_separator_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_chunk_separator_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_chunk_separator_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_chunk_size_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_chunk_size_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_chunk_size_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_chunk_size_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_compute_ppl_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_compute_ppl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_compute_ppl_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_compute_ppl_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_cont_batching_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_cont_batching_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cont_batching_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cont_batching_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_context_files_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_context_files_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_context_files_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_context_files_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_control_vector_layer_end_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_control_vector_layer_end_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_control_vector_layer_end_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_control_vector_layer_end_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_control_vector_layer_start_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_control_vector_layer_start_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_control_vector_layer_start_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_control_vector_layer_start_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_control_vectors_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_control_vectors_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_control_vectors_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_control_vectors_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_conversation_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_conversation_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_conversation_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_conversation_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_cvector_dimre_method_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_dimre_method_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cvector_dimre_method_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_dimre_method_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_cvector_negative_file_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_negative_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cvector_negative_file_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_negative_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_cvector_outfile_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_outfile_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cvector_outfile_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_outfile_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_cvector_positive_file_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_positive_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_cvector_positive_file_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_cvector_positive_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_defrag_thold_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_defrag_thold_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_defrag_thold_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_defrag_thold_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_display_prompt_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_display_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_display_prompt_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_display_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_dump_kv_cache_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_dump_kv_cache_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_dump_kv_cache_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_dump_kv_cache_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_embd_normalize_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_embd_normalize_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_embd_normalize_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_embd_normalize_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_embd_out_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_embd_out_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_embd_out_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_embd_out_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_embd_sep_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_embd_sep_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_embd_sep_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_embd_sep_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_embedding_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_embedding_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_embedding_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_embedding_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_enable_chat_template_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_enable_chat_template_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_enable_chat_template_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_enable_chat_template_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_endpoint_metrics_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_endpoint_metrics_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_endpoint_metrics_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_endpoint_metrics_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_endpoint_slots_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_endpoint_slots_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_endpoint_slots_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_endpoint_slots_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_escape_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_escape_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_escape_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_escape_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_flash_attn_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_flash_attn_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_flash_attn_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_flash_attn_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_grp_attn_n_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_grp_attn_n_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_grp_attn_n_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_grp_attn_n_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_grp_attn_w_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_grp_attn_w_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_grp_attn_w_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_grp_attn_w_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_hellaswag_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_hellaswag_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_hellaswag_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_hellaswag_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_hellaswag_tasks_get()
static uint LlamaLibrary.libllama_libPINVOKE.gpt_params_hellaswag_tasks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_hellaswag_tasks_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_hellaswag_tasks_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
gpt_params_hf_file_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_hf_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_hf_file_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_hf_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_hf_repo_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_hf_repo_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_hf_repo_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_hf_repo_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_hf_token_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_hf_token_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_hf_token_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_hf_token_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_hostname_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_hostname_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_hostname_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_hostname_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_i_chunk_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_i_chunk_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_i_chunk_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_i_chunk_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_i_pos_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_i_pos_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_i_pos_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_i_pos_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_ignore_eos_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_ignore_eos_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_ignore_eos_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_ignore_eos_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_image_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_image_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_image_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_image_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_in_files_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_in_files_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_in_files_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_in_files_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_infill_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_infill_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_infill_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_infill_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_input_prefix_bos_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_input_prefix_bos_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_input_prefix_bos_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_input_prefix_bos_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_input_prefix_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_input_prefix_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_input_prefix_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_input_prefix_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_input_suffix_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_input_suffix_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_input_suffix_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_input_suffix_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_interactive_first_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_interactive_first_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_interactive_first_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_interactive_first_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_interactive_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_interactive_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_interactive_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_interactive_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_is_pp_shared_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_is_pp_shared_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_is_pp_shared_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_is_pp_shared_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_kl_divergence_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_kl_divergence_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_kl_divergence_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_kl_divergence_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_kv_overrides_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_kv_overrides_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_kv_overrides_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_kv_overrides_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_log_json_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_log_json_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_log_json_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_log_json_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_logdir_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_logdir_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_logdir_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_logdir_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_logits_all_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_logits_all_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_logits_all_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_logits_all_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_logits_file_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_logits_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_logits_file_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_logits_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_lookup_cache_dynamic_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_lookup_cache_dynamic_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_lookup_cache_dynamic_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_lookup_cache_dynamic_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_lookup_cache_static_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_lookup_cache_static_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_lookup_cache_static_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_lookup_cache_static_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_lora_adapter_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_lora_adapter_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_lora_adapter_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_lora_adapter_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_lora_outfile_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_lora_outfile_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_lora_outfile_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_lora_outfile_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_main_gpu_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_main_gpu_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_main_gpu_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_main_gpu_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_mmproj_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_mmproj_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_mmproj_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_mmproj_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_model_alias_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_model_alias_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_model_alias_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_model_alias_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_model_draft_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_model_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_model_draft_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_model_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_model_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_model_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_model_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_model_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_model_url_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_model_url_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_model_url_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_model_url_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_multiline_input_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_multiline_input_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_multiline_input_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_multiline_input_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_multiple_choice_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_multiple_choice_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_multiple_choice_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_multiple_choice_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_multiple_choice_tasks_get()
static uint LlamaLibrary.libllama_libPINVOKE.gpt_params_multiple_choice_tasks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_multiple_choice_tasks_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_multiple_choice_tasks_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
gpt_params_n_batch_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_batch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_batch_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_batch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_chunks_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_chunks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_chunks_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_chunks_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_ctx_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_ctx_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_ctx_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_ctx_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_draft_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_draft_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_gpu_layers_draft_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_gpu_layers_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_gpu_layers_draft_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_gpu_layers_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_gpu_layers_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_gpu_layers_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_gpu_layers_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_gpu_layers_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_junk_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_junk_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_junk_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_junk_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_keep_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_keep_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_keep_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_keep_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_out_freq_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_out_freq_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_out_freq_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_out_freq_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_parallel_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_parallel_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_parallel_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_parallel_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_pca_batch_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pca_batch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_pca_batch_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pca_batch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_pca_iterations_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pca_iterations_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_pca_iterations_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pca_iterations_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_pl_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_pl_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_n_pp_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pp_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_pp_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_pp_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_n_predict_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_predict_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_predict_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_predict_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_print_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_print_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_print_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_print_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_save_freq_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_save_freq_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_save_freq_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_save_freq_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_sequences_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_sequences_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_sequences_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_sequences_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_tg_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_n_tg_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_tg_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_tg_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_n_threads_batch_draft_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_batch_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_threads_batch_draft_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_batch_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_threads_batch_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_batch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_threads_batch_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_batch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_threads_draft_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_draft_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_threads_draft_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_draft_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_threads_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_threads_http_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_http_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_threads_http_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_http_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_threads_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_threads_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_n_ubatch_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_n_ubatch_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_n_ubatch_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_n_ubatch_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_no_kv_offload_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_no_kv_offload_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_no_kv_offload_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_no_kv_offload_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_numa_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_numa_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_numa_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_numa_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_out_file_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_out_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_out_file_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_out_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_p_split_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_p_split_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_p_split_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_p_split_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_path_prompt_cache_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_path_prompt_cache_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_path_prompt_cache_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_path_prompt_cache_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_pooling_type_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_pooling_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_pooling_type_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_pooling_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_port_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_port_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_port_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_port_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_ppl_output_type_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_ppl_output_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_ppl_output_type_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_ppl_output_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_ppl_stride_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_ppl_stride_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_ppl_stride_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_ppl_stride_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_process_output_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_process_output_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_process_output_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_process_output_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_prompt_cache_all_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_cache_all_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_prompt_cache_all_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_cache_all_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_prompt_cache_ro_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_cache_ro_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_prompt_cache_ro_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_cache_ro_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_prompt_file_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_file_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_prompt_file_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_file_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_prompt_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_prompt_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_public_path_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_public_path_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_public_path_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_public_path_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_rope_freq_base_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_rope_freq_base_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_rope_freq_base_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_rope_freq_base_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_rope_freq_scale_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_rope_freq_scale_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_rope_freq_scale_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_rope_freq_scale_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_rope_scaling_type_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_rope_scaling_type_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_rope_scaling_type_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_rope_scaling_type_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_rpc_servers_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_rpc_servers_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_rpc_servers_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_rpc_servers_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_seed_get()
static uint LlamaLibrary.libllama_libPINVOKE.gpt_params_seed_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_seed_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_seed_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
gpt_params_simple_io_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_simple_io_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_simple_io_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_simple_io_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_slot_prompt_similarity_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_slot_prompt_similarity_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_slot_prompt_similarity_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_slot_prompt_similarity_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_slot_save_path_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_slot_save_path_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_slot_save_path_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_slot_save_path_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_sparams_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_sparams_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_sparams_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_sparams_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_special_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_special_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_special_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_special_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_split_mode_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_split_mode_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_split_mode_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_split_mode_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_spm_infill_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_spm_infill_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_spm_infill_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_spm_infill_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_ssl_file_cert_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_ssl_file_cert_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_ssl_file_cert_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_ssl_file_cert_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_ssl_file_key_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_ssl_file_key_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_ssl_file_key_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_ssl_file_key_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_system_prompt_get()
static string LlamaLibrary.libllama_libPINVOKE.gpt_params_system_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_system_prompt_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_system_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
gpt_params_tensor_split_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.gpt_params_tensor_split_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_tensor_split_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_tensor_split_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
gpt_params_timeout_read_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_timeout_read_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_timeout_read_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_timeout_read_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_timeout_write_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_timeout_write_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_timeout_write_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_timeout_write_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_usage_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_usage_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_usage_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_usage_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_use_color_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_use_color_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_use_color_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_use_color_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_use_mlock_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_use_mlock_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_use_mlock_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_use_mlock_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_use_mmap_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_use_mmap_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_use_mmap_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_use_mmap_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_verbose_prompt_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_verbose_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_verbose_prompt_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_verbose_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_verbosity_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_verbosity_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_verbosity_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_verbosity_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
gpt_params_warmup_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_warmup_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_warmup_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_warmup_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_winogrande_get()
static bool LlamaLibrary.libllama_libPINVOKE.gpt_params_winogrande_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_winogrande_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_winogrande_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
gpt_params_winogrande_tasks_get()
static uint LlamaLibrary.libllama_libPINVOKE.gpt_params_winogrande_tasks_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_winogrande_tasks_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_winogrande_tasks_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
gpt_params_yarn_attn_factor_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_attn_factor_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_yarn_attn_factor_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_attn_factor_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_yarn_beta_fast_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_beta_fast_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_yarn_beta_fast_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_beta_fast_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_yarn_beta_slow_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_beta_slow_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_yarn_beta_slow_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_beta_slow_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_yarn_ext_factor_get()
static float LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_ext_factor_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_yarn_ext_factor_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_ext_factor_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
gpt_params_yarn_orig_ctx_get()
static int LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_orig_ctx_get (global::System.Runtime.InteropServices.HandleRef jarg1)
gpt_params_yarn_orig_ctx_set()
static void LlamaLibrary.libllama_libPINVOKE.gpt_params_yarn_orig_ctx_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Int32s_Add()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_Add (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.Add().
Int32s_AddRange()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
Referenced by LlamaLibrary.Int32s.AddRange().
Int32s_capacity()
static uint LlamaLibrary.libllama_libPINVOKE.Int32s_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Int32s.capacity().
Int32s_Clear()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Int32s.Clear().
Int32s_Contains()
static bool LlamaLibrary.libllama_libPINVOKE.Int32s_Contains (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.Contains().
Int32s_getitem()
static int LlamaLibrary.libllama_libPINVOKE.Int32s_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.getitem().
Int32s_getitemcopy()
static int LlamaLibrary.libllama_libPINVOKE.Int32s_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.getitemcopy().
Int32s_GetRange()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.Int32s_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Int32s.GetRange().
Int32s_IndexOf()
static int LlamaLibrary.libllama_libPINVOKE.Int32s_IndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.IndexOf().
Int32s_Insert()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Int32s.Insert().
Int32s_InsertRange()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.Int32s.InsertRange().
Int32s_LastIndexOf()
static int LlamaLibrary.libllama_libPINVOKE.Int32s_LastIndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.LastIndexOf().
Int32s_Remove()
static bool LlamaLibrary.libllama_libPINVOKE.Int32s_Remove (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.Remove().
Int32s_RemoveAt()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.RemoveAt().
Int32s_RemoveRange()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Int32s.RemoveRange().
Int32s_Repeat()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.Int32s_Repeat (int jarg1, int jarg2)
Referenced by LlamaLibrary.Int32s.Repeat().
Int32s_reserve()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
Referenced by LlamaLibrary.Int32s.reserve().
Int32s_Reverse__SWIG_0()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Int32s.Reverse().
Int32s_Reverse__SWIG_1()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Int32s.Reverse().
Int32s_setitem()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Int32s.setitem().
Int32s_SetRange()
static void LlamaLibrary.libllama_libPINVOKE.Int32s_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.Int32s.SetRange().
Int32s_size()
static uint LlamaLibrary.libllama_libPINVOKE.Int32s_size (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Int32s.size().
llama_sampling_params_cfg_negative_prompt_get()
static string LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_cfg_negative_prompt_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_cfg_negative_prompt_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_cfg_negative_prompt_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
llama_sampling_params_cfg_scale_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_cfg_scale_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_cfg_scale_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_cfg_scale_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_dynatemp_exponent_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_dynatemp_exponent_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_dynatemp_exponent_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_dynatemp_exponent_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_dynatemp_range_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_dynatemp_range_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_dynatemp_range_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_dynatemp_range_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_grammar_get()
static string LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_grammar_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_grammar_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_grammar_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
llama_sampling_params_logit_bias_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_logit_bias_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_logit_bias_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_logit_bias_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
llama_sampling_params_min_keep_get()
static int LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_min_keep_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_min_keep_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_min_keep_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
llama_sampling_params_min_p_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_min_p_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_min_p_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_min_p_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_mirostat_eta_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_mirostat_eta_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_mirostat_eta_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_mirostat_eta_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_mirostat_get()
static int LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_mirostat_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_mirostat_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_mirostat_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
llama_sampling_params_mirostat_tau_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_mirostat_tau_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_mirostat_tau_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_mirostat_tau_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_n_prev_get()
static int LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_n_prev_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_n_prev_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_n_prev_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
llama_sampling_params_n_probs_get()
static int LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_n_probs_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_n_probs_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_n_probs_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
llama_sampling_params_penalize_nl_get()
static bool LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalize_nl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_penalize_nl_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalize_nl_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
llama_sampling_params_penalty_freq_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_freq_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_penalty_freq_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_freq_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_penalty_last_n_get()
static int LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_last_n_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_penalty_last_n_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_last_n_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
llama_sampling_params_penalty_present_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_present_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_penalty_present_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_present_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_penalty_prompt_tokens_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_prompt_tokens_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_penalty_prompt_tokens_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_prompt_tokens_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
llama_sampling_params_penalty_repeat_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_repeat_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_penalty_repeat_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_penalty_repeat_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_samplers_sequence_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_samplers_sequence_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_samplers_sequence_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_samplers_sequence_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
llama_sampling_params_seed_get()
static uint LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_seed_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_seed_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_seed_set (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
llama_sampling_params_temp_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_temp_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_temp_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_temp_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_tfs_z_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_tfs_z_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_tfs_z_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_tfs_z_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_top_k_get()
static int LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_top_k_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_top_k_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_top_k_set (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
llama_sampling_params_top_p_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_top_p_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_top_p_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_top_p_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_typical_p_get()
static float LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_typical_p_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_typical_p_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_typical_p_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
llama_sampling_params_use_penalty_prompt_tokens_get()
static bool LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_use_penalty_prompt_tokens_get (global::System.Runtime.InteropServices.HandleRef jarg1)
llama_sampling_params_use_penalty_prompt_tokens_set()
static void LlamaLibrary.libllama_libPINVOKE.llama_sampling_params_use_penalty_prompt_tokens_set (global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2)
LlamaControlVectorLoadInfos_Add()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Add (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Add().
LlamaControlVectorLoadInfos_AddRange()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.AddRange().
LlamaControlVectorLoadInfos_capacity()
static uint LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.capacity().
LlamaControlVectorLoadInfos_Clear()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Clear().
LlamaControlVectorLoadInfos_getitem()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.getitem().
LlamaControlVectorLoadInfos_getitemcopy()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.getitemcopy().
LlamaControlVectorLoadInfos_GetRange()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.GetRange().
LlamaControlVectorLoadInfos_Insert()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Insert().
LlamaControlVectorLoadInfos_InsertRange()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.InsertRange().
LlamaControlVectorLoadInfos_RemoveAt()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.RemoveAt().
LlamaControlVectorLoadInfos_RemoveRange()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.RemoveRange().
LlamaControlVectorLoadInfos_Repeat()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Repeat (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Repeat().
LlamaControlVectorLoadInfos_reserve()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.reserve().
LlamaControlVectorLoadInfos_Reverse__SWIG_0()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Reverse().
LlamaControlVectorLoadInfos_Reverse__SWIG_1()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Reverse().
LlamaControlVectorLoadInfos_setitem()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.setitem().
LlamaControlVectorLoadInfos_SetRange()
static void LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.SetRange().
LlamaControlVectorLoadInfos_size()
static uint LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_size (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.size().
LlamaInfrence_Echo()
static void LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_Echo (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.LlamaInfrence.Echo().
LlamaInfrence_Generate()
static bool LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_Generate (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.LlamaInfrence.Generate().
LlamaInfrence_GetGenerated()
static string LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_GetGenerated (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaInfrence.GetGenerated().
LlamaInfrence_GetParameters()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_GetParameters (string jarg1)
Referenced by LlamaLibrary.LlamaInfrence.GetParameters().
LlamaInfrence_pImpl_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_pImpl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
LlamaInfrence_pImpl_set()
static void LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_pImpl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
LlamaInfrence_Stop()
static void LlamaLibrary.libllama_libPINVOKE.LlamaInfrence_Stop (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.LlamaInfrence.Stop().
LoggingContext_pImpl_get()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.LoggingContext_pImpl_get (global::System.Runtime.InteropServices.HandleRef jarg1)
LoggingContext_pImpl_set()
static void LlamaLibrary.libllama_libPINVOKE.LoggingContext_pImpl_set (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
new_AsyncLlamaInfrence()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_AsyncLlamaInfrence ()
new_FileWrapper()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_FileWrapper ()
new_gpt_params()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_gpt_params ()
new_Int32s__SWIG_0()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_Int32s__SWIG_0 ()
new_Int32s__SWIG_1()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_Int32s__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
new_Int32s__SWIG_2()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_Int32s__SWIG_2 (int jarg1)
new_llama_sampling_params()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_llama_sampling_params ()
new_LlamaControlVectorLoadInfos__SWIG_0()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_LlamaControlVectorLoadInfos__SWIG_0 ()
new_LlamaControlVectorLoadInfos__SWIG_1()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_LlamaControlVectorLoadInfos__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
new_LlamaControlVectorLoadInfos__SWIG_2()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_LlamaControlVectorLoadInfos__SWIG_2 (int jarg1)
new_LlamaInfrence()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_LlamaInfrence (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
new_LoggingContext()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_LoggingContext ()
new_StringAndFloat__SWIG_0()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_StringAndFloat__SWIG_0 ()
new_StringAndFloat__SWIG_1()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_StringAndFloat__SWIG_1 (string jarg1, float jarg2)
new_StringAndFloat__SWIG_2()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_StringAndFloat__SWIG_2 (global::System.Runtime.InteropServices.HandleRef jarg1)
new_Strings__SWIG_0()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_Strings__SWIG_0 ()
new_Strings__SWIG_1()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_Strings__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
new_Strings__SWIG_2()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_Strings__SWIG_2 (int jarg1)
new_StringsAndFloats__SWIG_0()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_StringsAndFloats__SWIG_0 ()
new_StringsAndFloats__SWIG_1()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_StringsAndFloats__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1)
new_StringsAndFloats__SWIG_2()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.new_StringsAndFloats__SWIG_2 (int jarg1)
StringAndFloat_first_get()
static string LlamaLibrary.libllama_libPINVOKE.StringAndFloat_first_get (global::System.Runtime.InteropServices.HandleRef jarg1)
StringAndFloat_first_set()
static void LlamaLibrary.libllama_libPINVOKE.StringAndFloat_first_set (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
StringAndFloat_second_get()
static float LlamaLibrary.libllama_libPINVOKE.StringAndFloat_second_get (global::System.Runtime.InteropServices.HandleRef jarg1)
StringAndFloat_second_set()
static void LlamaLibrary.libllama_libPINVOKE.StringAndFloat_second_set (global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2)
Strings_Add()
static void LlamaLibrary.libllama_libPINVOKE.Strings_Add (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.Strings.Add().
Strings_AddRange()
static void LlamaLibrary.libllama_libPINVOKE.Strings_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
Referenced by LlamaLibrary.Strings.AddRange().
Strings_capacity()
static uint LlamaLibrary.libllama_libPINVOKE.Strings_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Strings.capacity().
Strings_Clear()
static void LlamaLibrary.libllama_libPINVOKE.Strings_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Strings.Clear().
Strings_Contains()
static bool LlamaLibrary.libllama_libPINVOKE.Strings_Contains (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.Strings.Contains().
Strings_getitem()
static string LlamaLibrary.libllama_libPINVOKE.Strings_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Strings.getitem().
Strings_getitemcopy()
static string LlamaLibrary.libllama_libPINVOKE.Strings_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Strings.getitemcopy().
Strings_GetRange()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.Strings_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Strings.GetRange().
Strings_IndexOf()
static int LlamaLibrary.libllama_libPINVOKE.Strings_IndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.Strings.IndexOf().
Strings_Insert()
static void LlamaLibrary.libllama_libPINVOKE.Strings_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3)
Referenced by LlamaLibrary.Strings.Insert().
Strings_InsertRange()
static void LlamaLibrary.libllama_libPINVOKE.Strings_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.Strings.InsertRange().
Strings_LastIndexOf()
static int LlamaLibrary.libllama_libPINVOKE.Strings_LastIndexOf (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.Strings.LastIndexOf().
Strings_Remove()
static bool LlamaLibrary.libllama_libPINVOKE.Strings_Remove (global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2)
Referenced by LlamaLibrary.Strings.Remove().
Strings_RemoveAt()
static void LlamaLibrary.libllama_libPINVOKE.Strings_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.Strings.RemoveAt().
Strings_RemoveRange()
static void LlamaLibrary.libllama_libPINVOKE.Strings_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Strings.RemoveRange().
Strings_Repeat()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.Strings_Repeat (string jarg1, int jarg2)
Referenced by LlamaLibrary.Strings.Repeat().
Strings_reserve()
static void LlamaLibrary.libllama_libPINVOKE.Strings_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
Referenced by LlamaLibrary.Strings.reserve().
Strings_Reverse__SWIG_0()
static void LlamaLibrary.libllama_libPINVOKE.Strings_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Strings.Reverse().
Strings_Reverse__SWIG_1()
static void LlamaLibrary.libllama_libPINVOKE.Strings_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.Strings.Reverse().
Strings_setitem()
static void LlamaLibrary.libllama_libPINVOKE.Strings_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3)
Referenced by LlamaLibrary.Strings.setitem().
Strings_SetRange()
static void LlamaLibrary.libllama_libPINVOKE.Strings_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.Strings.SetRange().
Strings_size()
static uint LlamaLibrary.libllama_libPINVOKE.Strings_size (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.Strings.size().
StringsAndFloats_Add()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Add (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
Referenced by LlamaLibrary.StringsAndFloats.Add().
StringsAndFloats_AddRange()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_AddRange (global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2)
Referenced by LlamaLibrary.StringsAndFloats.AddRange().
StringsAndFloats_capacity()
static uint LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_capacity (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.StringsAndFloats.capacity().
StringsAndFloats_Clear()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Clear (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.StringsAndFloats.Clear().
StringsAndFloats_getitem()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_getitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.StringsAndFloats.getitem().
StringsAndFloats_getitemcopy()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_getitemcopy (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.StringsAndFloats.getitemcopy().
StringsAndFloats_GetRange()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_GetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.StringsAndFloats.GetRange().
StringsAndFloats_Insert()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Insert (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.StringsAndFloats.Insert().
StringsAndFloats_InsertRange()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_InsertRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.StringsAndFloats.InsertRange().
StringsAndFloats_RemoveAt()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_RemoveAt (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.StringsAndFloats.RemoveAt().
StringsAndFloats_RemoveRange()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_RemoveRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.StringsAndFloats.RemoveRange().
StringsAndFloats_Repeat()
static global.System.IntPtr LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Repeat (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2)
Referenced by LlamaLibrary.StringsAndFloats.Repeat().
StringsAndFloats_reserve()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_reserve (global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2)
Referenced by LlamaLibrary.StringsAndFloats.reserve().
StringsAndFloats_Reverse__SWIG_0()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Reverse__SWIG_0 (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.StringsAndFloats.Reverse().
StringsAndFloats_Reverse__SWIG_1()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Reverse__SWIG_1 (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3)
Referenced by LlamaLibrary.StringsAndFloats.Reverse().
StringsAndFloats_setitem()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_setitem (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.StringsAndFloats.setitem().
StringsAndFloats_SetRange()
static void LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_SetRange (global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3)
Referenced by LlamaLibrary.StringsAndFloats.SetRange().
StringsAndFloats_size()
static uint LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_size (global::System.Runtime.InteropServices.HandleRef jarg1)
Referenced by LlamaLibrary.StringsAndFloats.size().
Member Data Documentation
LIBRARY_NAME
const string LlamaLibrary.libllama_libPINVOKE.LIBRARY_NAME = "libllama_lib" static
swigExceptionHelper
SWIGExceptionHelper LlamaLibrary.libllama_libPINVOKE.swigExceptionHelper = new SWIGExceptionHelper() static protected
swigStringHelper
SWIGStringHelper LlamaLibrary.libllama_libPINVOKE.swigStringHelper = new SWIGStringHelper() static protected
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/libllama_libPINVOKE.cs