StyledLines from testedlines.com: C# docs: LlamaLibrary.Strings Class Reference
LlamaLibrary.Strings Class Reference
Classes
class StringsEnumerator
Public Member Functions
void Add (string x)
void AddRange (Strings values)
void Clear ()
bool Contains (string value)
void CopyTo (int index, string[] array, int arrayIndex, int count)
void CopyTo (string[] array)
void CopyTo (string[] array, int arrayIndex)
virtual void Dispose ()
StringsEnumerator GetEnumerator ()
Strings GetRange (int index, int count)
int IndexOf (string value)
void Insert (int index, string x)
void InsertRange (int index, Strings values)
int LastIndexOf (string value)
bool Remove (string value)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, Strings values)
Strings ()
Strings (global::System.Collections.Generic.IEnumerable< string > c)
Strings (global::System.Collections.IEnumerable c)
Strings (int capacity)
Strings (Strings other)
string[] ToArray ()
Static Public Member Functions
static Strings Repeat (string value, int count)
Protected Attributes
bool swigCMemOwn
Package Functions
Strings (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (Strings obj)
Properties
int Capacity [get, set]
int Count [get]
bool IsFixedSize [get]
bool IsReadOnly [get]
bool IsSynchronized [get]
string this[int index] [get, set]
Private Member Functions
uint capacity ()
global::System.Collections.Generic.IEnumerator< string > global::System.Collections.Generic.IEnumerable< string >. GetEnumerator ()
global::System.Collections.IEnumerator global::System.Collections.IEnumerable. GetEnumerator ()
string getitem (int index)
string getitemcopy (int index)
void reserve (uint n)
void setitem (int index, string value)
uint size ()
~Strings ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
Strings() [1/6]
LlamaLibrary.Strings.Strings (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.Strings.swigCMemOwn, and LlamaLibrary.Strings.swigCPtr.
~Strings()
LlamaLibrary.Strings.~Strings () private
References LlamaLibrary.Strings.Dispose().
Strings() [2/6]
LlamaLibrary.Strings.Strings (global::System::Collections::IEnumerable c)
References LlamaLibrary.Strings.Add().
Strings() [3/6]
LlamaLibrary.Strings.Strings (global::System::Collections::Generic::IEnumerable< string > c)
References LlamaLibrary.Strings.Add().
Strings() [4/6]
LlamaLibrary.Strings.Strings ()
Referenced by LlamaLibrary.Strings.GetRange(), and LlamaLibrary.Strings.Repeat().
Strings() [5/6]
LlamaLibrary.Strings.Strings (Strings other)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Strings() [6/6]
LlamaLibrary.Strings.Strings (int capacity)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Member Function Documentation
Add()
void LlamaLibrary.Strings.Add (string x)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_Add(), and LlamaLibrary.Strings.swigCPtr.
Referenced by LlamaLibrary.Strings.Strings(), and LlamaLibrary.Strings.Strings().
AddRange()
void LlamaLibrary.Strings.AddRange (Strings values)
References LlamaLibrary.Strings.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_AddRange(), and LlamaLibrary.Strings.swigCPtr.
capacity()
uint LlamaLibrary.Strings.capacity () private
References LlamaLibrary.libllama_libPINVOKE.Strings_capacity(), and LlamaLibrary.Strings.swigCPtr.
Clear()
void LlamaLibrary.Strings.Clear ()
References LlamaLibrary.libllama_libPINVOKE.Strings_Clear(), and LlamaLibrary.Strings.swigCPtr.
Contains()
bool LlamaLibrary.Strings.Contains (string value)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_Contains(), and LlamaLibrary.Strings.swigCPtr.
CopyTo() [1/3]
void LlamaLibrary.Strings.CopyTo (int index, string[] array, int arrayIndex, int count)
References LlamaLibrary.Strings.Count, and LlamaLibrary.Strings.getitemcopy().
CopyTo() [2/3]
void LlamaLibrary.Strings.CopyTo (string[] array)
References LlamaLibrary.Strings.CopyTo(), and LlamaLibrary.Strings.Count.
Referenced by LlamaLibrary.Strings.CopyTo(), LlamaLibrary.Strings.CopyTo(), and LlamaLibrary.Strings.ToArray().
CopyTo() [3/3]
void LlamaLibrary.Strings.CopyTo (string[] array, int arrayIndex)
References LlamaLibrary.Strings.CopyTo(), and LlamaLibrary.Strings.Count.
Dispose()
virtual void LlamaLibrary.Strings.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_Strings(), LlamaLibrary.Strings.swigCMemOwn, and LlamaLibrary.Strings.swigCPtr.
Referenced by LlamaLibrary.Strings.~Strings().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.Strings.getCPtr (Strings obj) static package
References LlamaLibrary.Strings.swigCPtr.
Referenced by LlamaLibrary.Strings.AddRange(), LlamaLibrary.Strings.InsertRange(), and LlamaLibrary.Strings.SetRange().
GetEnumerator() [1/3]
global.System.Collections.Generic.IEnumerator< string > global.System.Collections.Generic.IEnumerable< string >. LlamaLibrary.Strings.GetEnumerator () private
GetEnumerator() [2/3]
global.System.Collections.IEnumerator global.System.Collections.IEnumerable. LlamaLibrary.Strings.GetEnumerator () private
GetEnumerator() [3/3]
StringsEnumerator LlamaLibrary.Strings.GetEnumerator ()
getitem()
string LlamaLibrary.Strings.getitem (int index) private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_getitem(), and LlamaLibrary.Strings.swigCPtr.
getitemcopy()
string LlamaLibrary.Strings.getitemcopy (int index) private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_getitemcopy(), and LlamaLibrary.Strings.swigCPtr.
Referenced by LlamaLibrary.Strings.CopyTo().
GetRange()
Strings LlamaLibrary.Strings.GetRange (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.Strings.Strings(), LlamaLibrary.libllama_libPINVOKE.Strings_GetRange(), and LlamaLibrary.Strings.swigCPtr.
IndexOf()
int LlamaLibrary.Strings.IndexOf (string value)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_IndexOf(), and LlamaLibrary.Strings.swigCPtr.
Insert()
void LlamaLibrary.Strings.Insert (int index, string x)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_Insert(), and LlamaLibrary.Strings.swigCPtr.
InsertRange()
void LlamaLibrary.Strings.InsertRange (int index, Strings values)
References LlamaLibrary.Strings.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_InsertRange(), and LlamaLibrary.Strings.swigCPtr.
LastIndexOf()
int LlamaLibrary.Strings.LastIndexOf (string value)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_LastIndexOf(), and LlamaLibrary.Strings.swigCPtr.
Remove()
bool LlamaLibrary.Strings.Remove (string value)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_Remove(), and LlamaLibrary.Strings.swigCPtr.
RemoveAt()
void LlamaLibrary.Strings.RemoveAt (int index)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_RemoveAt(), and LlamaLibrary.Strings.swigCPtr.
RemoveRange()
void LlamaLibrary.Strings.RemoveRange (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_RemoveRange(), and LlamaLibrary.Strings.swigCPtr.
Repeat()
static Strings LlamaLibrary.Strings.Repeat (string value, int count) static
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.Strings.Strings(), and LlamaLibrary.libllama_libPINVOKE.Strings_Repeat().
reserve()
void LlamaLibrary.Strings.reserve (uint n) private
References LlamaLibrary.libllama_libPINVOKE.Strings_reserve(), and LlamaLibrary.Strings.swigCPtr.
Reverse() [1/2]
void LlamaLibrary.Strings.Reverse ()
References LlamaLibrary.libllama_libPINVOKE.Strings_Reverse__SWIG_0(), and LlamaLibrary.Strings.swigCPtr.
Reverse() [2/2]
void LlamaLibrary.Strings.Reverse (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_Reverse__SWIG_1(), and LlamaLibrary.Strings.swigCPtr.
setitem()
void LlamaLibrary.Strings.setitem (int index, string value) private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_setitem(), and LlamaLibrary.Strings.swigCPtr.
SetRange()
void LlamaLibrary.Strings.SetRange (int index, Strings values)
References LlamaLibrary.Strings.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.Strings_SetRange(), and LlamaLibrary.Strings.swigCPtr.
size()
uint LlamaLibrary.Strings.size () private
References LlamaLibrary.libllama_libPINVOKE.Strings_size(), and LlamaLibrary.Strings.swigCPtr.
Referenced by LlamaLibrary.Strings.StringsEnumerator.MoveNext().
ToArray()
string[] LlamaLibrary.Strings.ToArray ()
References LlamaLibrary.Strings.CopyTo(), and LlamaLibrary.Strings.Count.
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.Strings.swigCMemOwn protected
Referenced by LlamaLibrary.Strings.Dispose(), and LlamaLibrary.Strings.Strings().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.Strings.swigCPtr private
Referenced by LlamaLibrary.Strings.Add(), LlamaLibrary.Strings.AddRange(), LlamaLibrary.Strings.capacity(), LlamaLibrary.Strings.Clear(), LlamaLibrary.Strings.Contains(), LlamaLibrary.Strings.Dispose(), LlamaLibrary.Strings.getCPtr(), LlamaLibrary.Strings.getitem(), LlamaLibrary.Strings.getitemcopy(), LlamaLibrary.Strings.GetRange(), LlamaLibrary.Strings.IndexOf(), LlamaLibrary.Strings.Insert(), LlamaLibrary.Strings.InsertRange(), LlamaLibrary.Strings.LastIndexOf(), LlamaLibrary.Strings.Remove(), LlamaLibrary.Strings.RemoveAt(), LlamaLibrary.Strings.RemoveRange(), LlamaLibrary.Strings.reserve(), LlamaLibrary.Strings.Reverse(), LlamaLibrary.Strings.Reverse(), LlamaLibrary.Strings.setitem(), LlamaLibrary.Strings.SetRange(), LlamaLibrary.Strings.size(), and LlamaLibrary.Strings.Strings().
Property Documentation
Capacity
int LlamaLibrary.Strings.Capacity get set
Count
int LlamaLibrary.Strings.Count get
Referenced by LlamaLibrary.Strings.CopyTo(), LlamaLibrary.Strings.CopyTo(), LlamaLibrary.Strings.CopyTo(), LlamaLibrary.Strings.StringsEnumerator.MoveNext(), LlamaLibrary.Strings.StringsEnumerator.Reset(), LlamaLibrary.Strings.StringsEnumerator.StringsEnumerator(), and LlamaLibrary.Strings.ToArray().
IsFixedSize
bool LlamaLibrary.Strings.IsFixedSize get
IsReadOnly
bool LlamaLibrary.Strings.IsReadOnly get
IsSynchronized
bool LlamaLibrary.Strings.IsSynchronized get
this[int index]
string LlamaLibrary.Strings.this[int index] get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/Strings.cs