StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper Class Reference
Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper Class Reference
Private Member Functions
void OnDialogTextChanged (string newDialogText)
void OnDialogTextExternalUpdate (string newDialogText)
void Start ()
Private Attributes
TMP_InputField dialogInputField
DialogManager dialogManager
Member Function Documentation
OnDialogTextChanged()
void Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.OnDialogTextChanged (string newDialogText) private
References Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.dialogManager.
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.Start().
OnDialogTextExternalUpdate()
void Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.OnDialogTextExternalUpdate (string newDialogText) private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.Start().
Start()
void Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.Start () private
References Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.dialogInputField, Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.dialogManager, Assets.StyledLines.Runtime.DialogUtils.DialogManager.DialogText, Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.OnDialogTextChanged(), Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.OnDialogTextExternalUpdate(), and Assets.StyledLines.Runtime.DialogUtils.DialogManager.OnDialogUpdateEvent.
Member Data Documentation
dialogInputField
TMP_InputField Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.dialogInputField private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.Start().
dialogManager
DialogManager Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.dialogManager private
Referenced by Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.OnDialogTextChanged(), and Assets.StyledLines.Runtime.DialogUtils.DialogTextMapper.Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/DialogUtils/DialogTextMapper.cs