StyledLines from testedlines.com: C# docs: LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper Class Reference
LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper Class Reference
Public Member Functions
delegate void ExceptionArgumentDelegate (string message, string paramName)
delegate void ExceptionDelegate (string message)
static void SWIGRegisterExceptionCallbacks_libllama_lib (ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
static void SWIGRegisterExceptionCallbacksArgument_libllama_lib (ExceptionArgumentDelegate argumentDelegate, ExceptionArgumentDelegate argumentNullDelegate, ExceptionArgumentDelegate argumentOutOfRangeDelegate)
Static Private Member Functions
static void SetPendingApplicationException (string message)
static void SetPendingArgumentException (string message, string paramName)
static void SetPendingArgumentNullException (string message, string paramName)
static void SetPendingArgumentOutOfRangeException (string message, string paramName)
static void SetPendingArithmeticException (string message)
static void SetPendingDivideByZeroException (string message)
static void SetPendingIndexOutOfRangeException (string message)
static void SetPendingInvalidCastException (string message)
static void SetPendingInvalidOperationException (string message)
static void SetPendingIOException (string message)
static void SetPendingNullReferenceException (string message)
static void SetPendingOutOfMemoryException (string message)
static void SetPendingOverflowException (string message)
static void SetPendingSystemException (string message)
static SWIGExceptionHelper ()
Static Private Attributes
static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException)
static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException)
static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException)
static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException)
static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException)
static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException)
static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException)
static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException)
static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException)
static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException)
static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException)
static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException)
static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException)
static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException)
Constructor & Destructor Documentation
SWIGExceptionHelper()
static LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper () static private
References LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.applicationDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.argumentDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.argumentNullDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.argumentOutOfRangeDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.arithmeticDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.divideByZeroDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.indexOutOfRangeDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.invalidCastDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.invalidOperationDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.ioDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.nullReferenceDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.outOfMemoryDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.overflowDelegate, LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_libllama_lib(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacksArgument_libllama_lib(), and LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.systemDelegate.
Member Function Documentation
ExceptionArgumentDelegate()
delegate void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.ExceptionArgumentDelegate (string message, string paramName)
ExceptionDelegate()
delegate void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.ExceptionDelegate (string message)
SetPendingApplicationException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingApplicationException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingArgumentException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentException (string message, string paramName) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingArgumentNullException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentNullException (string message, string paramName) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingArgumentOutOfRangeException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentOutOfRangeException (string message, string paramName) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingArithmeticException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArithmeticException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingDivideByZeroException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingDivideByZeroException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingIndexOutOfRangeException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingIndexOutOfRangeException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingInvalidCastException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingInvalidCastException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingInvalidOperationException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingInvalidOperationException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingIOException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingIOException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingNullReferenceException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingNullReferenceException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingOutOfMemoryException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingOutOfMemoryException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingOverflowException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingOverflowException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SetPendingSystemException()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingSystemException (string message) static private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
SWIGRegisterExceptionCallbacks_libllama_lib()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_libllama_lib (ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
SWIGRegisterExceptionCallbacksArgument_libllama_lib()
static void LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacksArgument_libllama_lib (ExceptionArgumentDelegate argumentDelegate, ExceptionArgumentDelegate argumentNullDelegate, ExceptionArgumentDelegate argumentOutOfRangeDelegate)
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
Member Data Documentation
applicationDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.applicationDelegate = new ExceptionDelegate(SetPendingApplicationException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
argumentDelegate
ExceptionArgumentDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
argumentNullDelegate
ExceptionArgumentDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
argumentOutOfRangeDelegate
ExceptionArgumentDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
arithmeticDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
divideByZeroDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
indexOutOfRangeDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
invalidCastDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
invalidOperationDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
ioDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.ioDelegate = new ExceptionDelegate(SetPendingIOException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
nullReferenceDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
outOfMemoryDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
overflowDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.overflowDelegate = new ExceptionDelegate(SetPendingOverflowException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
systemDelegate
ExceptionDelegate LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.systemDelegate = new ExceptionDelegate(SetPendingSystemException) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SWIGExceptionHelper().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/libllama_libPINVOKE.cs