StyledLines from testedlines.com: C# docs: LlamaLibrary.llama_sampling_params Class Reference
LlamaLibrary.llama_sampling_params Class Reference
Public Member Functions
virtual void Dispose ()
llama_sampling_params ()
Protected Attributes
bool swigCMemOwn
Package Functions
llama_sampling_params (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (llama_sampling_params obj)
Properties
string cfg_negative_prompt [get, set]
float cfg_scale [get, set]
float dynatemp_exponent [get, set]
float dynatemp_range [get, set]
string grammar [get, set]
SWIGTYPE_p_std__unordered_mapT_llama_token_float_t logit_bias [get, set]
int min_keep [get, set]
float min_p [get, set]
int mirostat [get, set]
float mirostat_eta [get, set]
float mirostat_tau [get, set]
int n_prev [get, set]
int n_probs [get, set]
bool penalize_nl [get, set]
float penalty_freq [get, set]
int penalty_last_n [get, set]
float penalty_present [get, set]
SWIGTYPE_p_std__vectorT_llama_token_t penalty_prompt_tokens [get, set]
float penalty_repeat [get, set]
SWIGTYPE_p_std__vectorT_llama_sampler_type_t samplers_sequence [get, set]
uint seed [get, set]
float temp [get, set]
float tfs_z [get, set]
int top_k [get, set]
float top_p [get, set]
float typical_p [get, set]
bool use_penalty_prompt_tokens [get, set]
Private Member Functions
~llama_sampling_params ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
llama_sampling_params() [1/2]
LlamaLibrary.llama_sampling_params.llama_sampling_params (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.llama_sampling_params.swigCMemOwn, and LlamaLibrary.llama_sampling_params.swigCPtr.
~llama_sampling_params()
LlamaLibrary.llama_sampling_params.~llama_sampling_params () private
References LlamaLibrary.llama_sampling_params.Dispose().
llama_sampling_params() [2/2]
LlamaLibrary.llama_sampling_params.llama_sampling_params ()
Member Function Documentation
Dispose()
virtual void LlamaLibrary.llama_sampling_params.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_llama_sampling_params(), LlamaLibrary.llama_sampling_params.swigCMemOwn, and LlamaLibrary.llama_sampling_params.swigCPtr.
Referenced by LlamaLibrary.llama_sampling_params.~llama_sampling_params().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.llama_sampling_params.getCPtr (llama_sampling_params obj) static package
References LlamaLibrary.llama_sampling_params.swigCPtr.
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.llama_sampling_params.swigCMemOwn protected
Referenced by LlamaLibrary.llama_sampling_params.Dispose(), and LlamaLibrary.llama_sampling_params.llama_sampling_params().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.llama_sampling_params.swigCPtr private
Referenced by LlamaLibrary.llama_sampling_params.Dispose(), LlamaLibrary.llama_sampling_params.getCPtr(), and LlamaLibrary.llama_sampling_params.llama_sampling_params().
Property Documentation
cfg_negative_prompt
string LlamaLibrary.llama_sampling_params.cfg_negative_prompt get set
cfg_scale
float LlamaLibrary.llama_sampling_params.cfg_scale get set
dynatemp_exponent
float LlamaLibrary.llama_sampling_params.dynatemp_exponent get set
dynatemp_range
float LlamaLibrary.llama_sampling_params.dynatemp_range get set
grammar
string LlamaLibrary.llama_sampling_params.grammar get set
logit_bias
SWIGTYPE_p_std__unordered_mapT_llama_token_float_t LlamaLibrary.llama_sampling_params.logit_bias get set
min_keep
int LlamaLibrary.llama_sampling_params.min_keep get set
min_p
float LlamaLibrary.llama_sampling_params.min_p get set
mirostat
int LlamaLibrary.llama_sampling_params.mirostat get set
mirostat_eta
float LlamaLibrary.llama_sampling_params.mirostat_eta get set
mirostat_tau
float LlamaLibrary.llama_sampling_params.mirostat_tau get set
n_prev
int LlamaLibrary.llama_sampling_params.n_prev get set
n_probs
int LlamaLibrary.llama_sampling_params.n_probs get set
penalize_nl
bool LlamaLibrary.llama_sampling_params.penalize_nl get set
penalty_freq
float LlamaLibrary.llama_sampling_params.penalty_freq get set
penalty_last_n
int LlamaLibrary.llama_sampling_params.penalty_last_n get set
penalty_present
float LlamaLibrary.llama_sampling_params.penalty_present get set
penalty_prompt_tokens
SWIGTYPE_p_std__vectorT_llama_token_t LlamaLibrary.llama_sampling_params.penalty_prompt_tokens get set
penalty_repeat
float LlamaLibrary.llama_sampling_params.penalty_repeat get set
samplers_sequence
SWIGTYPE_p_std__vectorT_llama_sampler_type_t LlamaLibrary.llama_sampling_params.samplers_sequence get set
seed
uint LlamaLibrary.llama_sampling_params.seed get set
temp
float LlamaLibrary.llama_sampling_params.temp get set
tfs_z
float LlamaLibrary.llama_sampling_params.tfs_z get set
top_k
int LlamaLibrary.llama_sampling_params.top_k get set
top_p
float LlamaLibrary.llama_sampling_params.top_p get set
typical_p
float LlamaLibrary.llama_sampling_params.typical_p get set
use_penalty_prompt_tokens
bool LlamaLibrary.llama_sampling_params.use_penalty_prompt_tokens get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/llama_sampling_params.cs