StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.UIHelpers.LogToUI Class Reference
Assets.StyledLines.Runtime.UIHelpers.LogToUI Class Reference
Public Attributes
TMP_Text logText
Private Member Functions
void HandleLog (string logString, string stackTrace, LogType type)
void OnDisable ()
void OnEnable ()
Private Attributes
StringBuilder logBuilder = new()
Member Function Documentation
HandleLog()
void Assets.StyledLines.Runtime.UIHelpers.LogToUI.HandleLog (string logString, string stackTrace, LogType type) private
References Assets.StyledLines.Runtime.UIHelpers.LogToUI.logBuilder.
Referenced by Assets.StyledLines.Runtime.UIHelpers.LogToUI.OnDisable(), and Assets.StyledLines.Runtime.UIHelpers.LogToUI.OnEnable().
OnDisable()
void Assets.StyledLines.Runtime.UIHelpers.LogToUI.OnDisable () private
References Assets.StyledLines.Runtime.UIHelpers.LogToUI.HandleLog().
OnEnable()
void Assets.StyledLines.Runtime.UIHelpers.LogToUI.OnEnable () private
References Assets.StyledLines.Runtime.UIHelpers.LogToUI.HandleLog().
Member Data Documentation
logBuilder
StringBuilder Assets.StyledLines.Runtime.UIHelpers.LogToUI.logBuilder = new() private
Referenced by Assets.StyledLines.Runtime.UIHelpers.LogToUI.HandleLog().
logText
TMP_Text Assets.StyledLines.Runtime.UIHelpers.LogToUI.logText
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/LogToUI.cs