StyledLines from testedlines.com: C# docs: DialogManager Class Reference
DialogManager Class Reference
Classes
class Character
Serializable class representing a character in the dialog system.
Public Member Functions
DialogManager (bool loop)
Constructor for initializing the DialogManager with a loop setting.
void ReparseDialogAndStyles ()
Re-parses the dialog and styles when the dialog text changes.
Public Attributes
BinaryAsset binaryFileAsset
The asset containing binary data used by the model controller.
List< Character > Characters = new()
List of characters involved in the dialog.
string EditorUiDialogText
Dialog text shown in the editor UI for easy modification.
UnityEvent< GameObject, string > OnCharacterSpeakEvent
UnityEvent< string > OnDialogUpdateEvent
Properties
string DialogText [get, set]
Property for accessing and modifying the dialog text. It also triggers re-parsing and events when modified.
Private Member Functions
void CreateTextMeshesIfMissing ()
Ensures that each character has a TextMeshPro component for displaying dialog, creating one if necessary.
Bounds GetCombinedBounds (GameObject characterObject)
Calculates the combined bounds of all renderers in a character's GameObject.
IEnumerator< WaitForSeconds > HideTextAfterDelay (TextMeshPro textMesh, float delay)
Coroutine that hides the text by clearing it after a specified delay.
void ParseDialog ()
Parses the dialog text into individual lines based on a specific format.
IEnumerator ShowNextLine ()
Coroutine that displays the next line of dialog, handles looping, and manages the dialog's progression.
void ShowText (GameObject characterObject, string text)
Displays the specified text on the character's TextMeshPro component.
void Start ()
Called when the script starts; initializes the model controller, parses the dialog, and starts the dialog sequence.
void StartDialog ()
Starts the dialog sequence, setting the initial index and activating the dialog.
void Update ()
Called every frame; updates dialog progression and rotates text objects to face the camera.
Private Attributes
int _currentDialogIndex
float _defaultTextMeshHeightAboveAabb = 0.5f
bool _isDialogActive
bool _isUpdatingDialogText = false
Flag to prevent recursive dialog updates.
ModelController _llmController = null
Reference to the model controller for generating dialog responses.
bool _loop
Camera _mainCamera
float _minResponseDelay = 1000f
List< string > _parsedDialog = new List<string>()
float _timer
float _timeToShowLine = 2000f
bool isLineDisplaying = false
Constructor & Destructor Documentation
DialogManager()
DialogManager.DialogManager (bool loop)
Constructor for initializing the DialogManager with a loop setting.
Parameters
loop
Member Function Documentation
CreateTextMeshesIfMissing()
void DialogManager.CreateTextMeshesIfMissing () private
Ensures that each character has a TextMeshPro component for displaying dialog, creating one if necessary.
References _defaultTextMeshHeightAboveAabb, Characters, and GetCombinedBounds().
Referenced by Start().
GetCombinedBounds()
Bounds DialogManager.GetCombinedBounds (GameObject characterObject) private
Calculates the combined bounds of all renderers in a character's GameObject.
Parameters
characterObject
Returns
Referenced by CreateTextMeshesIfMissing().
HideTextAfterDelay()
IEnumerator< WaitForSeconds > DialogManager.HideTextAfterDelay (TextMeshPro textMesh, float delay) private
Coroutine that hides the text by clearing it after a specified delay.
Parameters
textMesh
delay
Returns
Referenced by ShowText().
ParseDialog()
void DialogManager.ParseDialog () private
Parses the dialog text into individual lines based on a specific format.
References _parsedDialog, and DialogText.
Referenced by ReparseDialogAndStyles(), and Start().
ReparseDialogAndStyles()
void DialogManager.ReparseDialogAndStyles ()
Re-parses the dialog and styles when the dialog text changes.
References ParseDialog().
Referenced by DialogTextAndCharacterStylesResetter.ResetStylesAndDialog().
ShowNextLine()
IEnumerator DialogManager.ShowNextLine () private
Coroutine that displays the next line of dialog, handles looping, and manages the dialog's progression.
Returns
References _currentDialogIndex, _isDialogActive, _llmController, _loop, _parsedDialog, Characters, ModelController.ExtractFirstPart(), LlamaLibrary.AsyncLlamaInfrence.GenerateAsync(), LlamaLibrary.AsyncLlamaInfrence.GetGenerationResults(), LlamaLibrary.AsyncLlamaInfrence.IsGenerationReady(), isLineDisplaying, ModelController.model, OnCharacterSpeakEvent, and ShowText().
Referenced by StartDialog(), and Update().
ShowText()
void DialogManager.ShowText (GameObject characterObject, string text) private
Displays the specified text on the character's TextMeshPro component.
Parameters
characterObject
text
References _timeToShowLine, and HideTextAfterDelay().
Referenced by ShowNextLine().
Start()
void DialogManager.Start () private
Called when the script starts; initializes the model controller, parses the dialog, and starts the dialog sequence.
References _llmController, _mainCamera, _parsedDialog, binaryFileAsset, CreateTextMeshesIfMissing(), DialogText, EditorUiDialogText, ParseDialog(), and StartDialog().
StartDialog()
void DialogManager.StartDialog () private
Starts the dialog sequence, setting the initial index and activating the dialog.
References _currentDialogIndex, _isDialogActive, and ShowNextLine().
Referenced by Start().
Update()
void DialogManager.Update () private
Called every frame; updates dialog progression and rotates text objects to face the camera.
References _isDialogActive, _mainCamera, _minResponseDelay, _timer, _timeToShowLine, Characters, isLineDisplaying, and ShowNextLine().
Member Data Documentation
_currentDialogIndex
int DialogManager._currentDialogIndex private
Referenced by ShowNextLine(), and StartDialog().
_defaultTextMeshHeightAboveAabb
float DialogManager._defaultTextMeshHeightAboveAabb = 0.5f private
Referenced by CreateTextMeshesIfMissing().
_isDialogActive
bool DialogManager._isDialogActive private
Referenced by ShowNextLine(), StartDialog(), and Update().
_isUpdatingDialogText
bool DialogManager._isUpdatingDialogText = false private
Flag to prevent recursive dialog updates.
_llmController
ModelController DialogManager._llmController = null private
Reference to the model controller for generating dialog responses.
Referenced by ShowNextLine(), and Start().
_loop
bool DialogManager._loop private
Referenced by ShowNextLine().
_mainCamera
Camera DialogManager._mainCamera private
Referenced by Start(), and Update().
_minResponseDelay
float DialogManager._minResponseDelay = 1000f private
Referenced by Update().
_parsedDialog
List<string> DialogManager._parsedDialog = new List<string>() private
Referenced by ParseDialog(), ShowNextLine(), and Start().
_timer
float DialogManager._timer private
Referenced by Update().
_timeToShowLine
float DialogManager._timeToShowLine = 2000f private
Referenced by ShowText(), and Update().
binaryFileAsset
BinaryAsset DialogManager.binaryFileAsset
The asset containing binary data used by the model controller.
Referenced by Start().
Characters
List<Character> DialogManager.Characters = new()
List of characters involved in the dialog.
Referenced by CreateTextMeshesIfMissing(), CharacterStyleMapper.OnCharacterSelected(), CharacterStyleMapper.OnStyleChanged(), DialogTextAndCharacterStylesResetter.ResetStylesAndDialog(), DialogTextAndCharacterStylesResetter.SaveInitialState(), ShowNextLine(), CharacterStyleMapper.Start(), and Update().
EditorUiDialogText
string DialogManager.EditorUiDialogText
Dialog text shown in the editor UI for easy modification.
Referenced by Start().
isLineDisplaying
bool DialogManager.isLineDisplaying = false private
Referenced by ShowNextLine(), and Update().
OnCharacterSpeakEvent
UnityEvent<GameObject, string> DialogManager.OnCharacterSpeakEvent
Referenced by ShowNextLine().
OnDialogUpdateEvent
UnityEvent<string> DialogManager.OnDialogUpdateEvent
Referenced by DialogTextMapper.Start().
Property Documentation
DialogText
string DialogManager.DialogText get set
Property for accessing and modifying the dialog text. It also triggers re-parsing and events when modified.
Referenced by ParseDialog(), DialogTextAndCharacterStylesResetter.SaveInitialState(), Start(), and DialogTextMapper.Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/DialogUtils/DialogManager.cs