StyledLines from testedlines.com: C# docs: LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper Class Reference
LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper Class Reference
Public Member Functions
static void SWIGRegisterStringCallback_libllama_lib (SWIGStringDelegate stringDelegate)
delegate string SWIGStringDelegate (string message)
Static Private Member Functions
static string CreateString (string cString)
static SWIGStringHelper ()
Static Private Attributes
static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString)
Constructor & Destructor Documentation
SWIGStringHelper()
static LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.SWIGStringHelper () static private
References LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.stringDelegate, and LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.SWIGRegisterStringCallback_libllama_lib().
Member Function Documentation
CreateString()
static string LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.CreateString (string cString) static private
SWIGRegisterStringCallback_libllama_lib()
static void LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.SWIGRegisterStringCallback_libllama_lib (SWIGStringDelegate stringDelegate)
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.SWIGStringHelper().
SWIGStringDelegate()
delegate string LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.SWIGStringDelegate (string message)
Member Data Documentation
stringDelegate
SWIGStringDelegate LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.stringDelegate = new SWIGStringDelegate(CreateString) static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGStringHelper.SWIGStringHelper().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/libllama_libPINVOKE.cs