StyledLines from testedlines.com: C# docs: ModelController Class Reference
ModelController Class Reference
Public Member Functions
ModelController (BinaryAsset binaryFileAsset)
Constructor for initializing the ModelController with a binary asset. The constructor sets up the model inference and prepares necessary callbacks.
Static Public Member Functions
static string ExtractFirstPart (string input, string stopText)
Static method to extract the first part of a string up to a specified stop text. If the stop text is found, the string is truncated before it; otherwise, it handles newline characters.
static string GetTempPath ()
Static method to get the appropriate temporary file path based on the platform. This method returns a platform-specific path where temporary files can be stored.
Public Attributes
AsyncLlamaInfrence model
Instance of the AsyncLlamaInference model used for generating responses asynchronously.
Private Attributes
LoggingContext _logger
Logger for capturing and handling logs during model operations.
gpt_params _settings
Settings for the GPT model, including paths and parameters.
Constructor & Destructor Documentation
ModelController()
ModelController.ModelController (BinaryAsset binaryFileAsset)
Constructor for initializing the ModelController with a binary asset. The constructor sets up the model inference and prepares necessary callbacks.
Parameters
binaryFileAsset
Exceptions
Exception
References _logger, _settings, BinaryAsset.data, GetTempPath(), model, LlamaLibrary.CallbackWrapper.RegisterTokenCallback(), LlamaLibrary.FileWrapper.Save(), and LlamaLibrary.AsyncLlamaInfrence.SetupAsync().
Member Function Documentation
ExtractFirstPart()
static string ModelController.ExtractFirstPart (string input, string stopText) static
Static method to extract the first part of a string up to a specified stop text. If the stop text is found, the string is truncated before it; otherwise, it handles newline characters.
Parameters
input
stopText
Returns
Referenced by MinimalExample.GenerateLine(), DialogManager.ShowNextLine(), and RunModelAsync.Update().
GetTempPath()
static string ModelController.GetTempPath () static
Static method to get the appropriate temporary file path based on the platform. This method returns a platform-specific path where temporary files can be stored.
Returns
Referenced by ModelController(), and RunModelAsync.Start().
Member Data Documentation
_logger
LoggingContext ModelController._logger private
Logger for capturing and handling logs during model operations.
Referenced by ModelController().
_settings
gpt_params ModelController._settings private
Settings for the GPT model, including paths and parameters.
Referenced by ModelController().
model
AsyncLlamaInfrence ModelController.model
Instance of the AsyncLlamaInference model used for generating responses asynchronously.
Referenced by MinimalExample.GenerateLine(), ModelController(), and DialogManager.ShowNextLine().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrenceUnity/ModelController.cs