StyledLines from testedlines.com: C# docs: LlamaLibrary.AsyncLlamaInfrence Class Reference
LlamaLibrary.AsyncLlamaInfrence Class Reference
Public Member Functions
AsyncLlamaInfrence ()
void ClearAllTasks ()
virtual void Dispose ()
int GenerateAsync (string prompt)
string GetGenerationResults (int task_id)
bool GetSetupResults (int task_id)
bool IsGenerationReady (int task_id)
int SetupAsync (LoggingContext logging, gpt_params cfg_params)
Protected Attributes
bool swigCMemOwn
Package Functions
AsyncLlamaInfrence (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (AsyncLlamaInfrence obj)
Properties
SWIGTYPE_p_AsyncLlamaInfrence__LlamaAsyncImpl pImpl [get, set]
Private Member Functions
~AsyncLlamaInfrence ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
AsyncLlamaInfrence() [1/2]
LlamaLibrary.AsyncLlamaInfrence.AsyncLlamaInfrence (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.AsyncLlamaInfrence.swigCMemOwn, and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
~AsyncLlamaInfrence()
LlamaLibrary.AsyncLlamaInfrence.~AsyncLlamaInfrence () private
References LlamaLibrary.AsyncLlamaInfrence.Dispose().
AsyncLlamaInfrence() [2/2]
LlamaLibrary.AsyncLlamaInfrence.AsyncLlamaInfrence ()
Member Function Documentation
ClearAllTasks()
void LlamaLibrary.AsyncLlamaInfrence.ClearAllTasks ()
References LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_ClearAllTasks(), and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
Dispose()
virtual void LlamaLibrary.AsyncLlamaInfrence.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_AsyncLlamaInfrence(), LlamaLibrary.AsyncLlamaInfrence.swigCMemOwn, and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnDestroy(), and LlamaLibrary.AsyncLlamaInfrence.~AsyncLlamaInfrence().
GenerateAsync()
int LlamaLibrary.AsyncLlamaInfrence.GenerateAsync (string prompt)
References LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_GenerateAsync(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.Generate().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.AsyncLlamaInfrence.getCPtr (AsyncLlamaInfrence obj) static package
References LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
GetGenerationResults()
string LlamaLibrary.AsyncLlamaInfrence.GetGenerationResults (int task_id)
References LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_GetGenerationResults(), and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.Update().
GetSetupResults()
bool LlamaLibrary.AsyncLlamaInfrence.GetSetupResults (int task_id)
References LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_GetSetupResults(), and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
IsGenerationReady()
bool LlamaLibrary.AsyncLlamaInfrence.IsGenerationReady (int task_id)
References LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_IsGenerationReady(), and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
SetupAsync()
int LlamaLibrary.AsyncLlamaInfrence.SetupAsync (LoggingContext logging, gpt_params cfg_params)
References LlamaLibrary.libllama_libPINVOKE.AsyncLlamaInfrence_SetupAsync(), LlamaLibrary.gpt_params.getCPtr(), LlamaLibrary.LoggingContext.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.AsyncLlamaInfrence.swigCPtr.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.DoSetup(), and Assets.StyledLines.Runtime.LlamaInfrenceUnity.ModelController.ModelController().
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.AsyncLlamaInfrence.swigCMemOwn protected
Referenced by LlamaLibrary.AsyncLlamaInfrence.AsyncLlamaInfrence(), and LlamaLibrary.AsyncLlamaInfrence.Dispose().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.AsyncLlamaInfrence.swigCPtr private
Referenced by LlamaLibrary.AsyncLlamaInfrence.AsyncLlamaInfrence(), LlamaLibrary.AsyncLlamaInfrence.ClearAllTasks(), LlamaLibrary.AsyncLlamaInfrence.Dispose(), LlamaLibrary.AsyncLlamaInfrence.GenerateAsync(), LlamaLibrary.AsyncLlamaInfrence.getCPtr(), LlamaLibrary.AsyncLlamaInfrence.GetGenerationResults(), LlamaLibrary.AsyncLlamaInfrence.GetSetupResults(), LlamaLibrary.AsyncLlamaInfrence.IsGenerationReady(), and LlamaLibrary.AsyncLlamaInfrence.SetupAsync().
Property Documentation
pImpl
SWIGTYPE_p_AsyncLlamaInfrence__LlamaAsyncImpl LlamaLibrary.AsyncLlamaInfrence.pImpl get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/AsyncLlamaInfrence.cs