StyledLines from testedlines.com: C# docs: LlamaLibrary.StringsAndFloats Class Reference
LlamaLibrary.StringsAndFloats Class Reference
Classes
class StringsAndFloatsEnumerator
Public Member Functions
void Add (StringAndFloat x)
void AddRange (StringsAndFloats values)
void Clear ()
void CopyTo (int index, StringAndFloat[] array, int arrayIndex, int count)
void CopyTo (StringAndFloat[] array)
void CopyTo (StringAndFloat[] array, int arrayIndex)
virtual void Dispose ()
StringsAndFloatsEnumerator GetEnumerator ()
StringsAndFloats GetRange (int index, int count)
void Insert (int index, StringAndFloat x)
void InsertRange (int index, StringsAndFloats values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, StringsAndFloats values)
StringsAndFloats ()
StringsAndFloats (global::System.Collections.Generic.IEnumerable< StringAndFloat > c)
StringsAndFloats (global::System.Collections.IEnumerable c)
StringsAndFloats (int capacity)
StringsAndFloats (StringsAndFloats other)
StringAndFloat[] ToArray ()
Static Public Member Functions
static StringsAndFloats Repeat (StringAndFloat value, int count)
Protected Attributes
bool swigCMemOwn
Package Functions
StringsAndFloats (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (StringsAndFloats obj)
Properties
int Capacity [get, set]
int Count [get]
bool IsFixedSize [get]
bool IsReadOnly [get]
bool IsSynchronized [get]
StringAndFloat this[int index] [get, set]
Private Member Functions
uint capacity ()
global::System.Collections.Generic.IEnumerator< StringAndFloat > global::System.Collections.Generic.IEnumerable< StringAndFloat >. GetEnumerator ()
global::System.Collections.IEnumerator global::System.Collections.IEnumerable. GetEnumerator ()
StringAndFloat getitem (int index)
StringAndFloat getitemcopy (int index)
void reserve (uint n)
void setitem (int index, StringAndFloat value)
uint size ()
~StringsAndFloats ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
StringsAndFloats() [1/6]
LlamaLibrary.StringsAndFloats.StringsAndFloats (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.StringsAndFloats.swigCMemOwn, and LlamaLibrary.StringsAndFloats.swigCPtr.
~StringsAndFloats()
LlamaLibrary.StringsAndFloats.~StringsAndFloats () private
References LlamaLibrary.StringsAndFloats.Dispose().
StringsAndFloats() [2/6]
LlamaLibrary.StringsAndFloats.StringsAndFloats (global::System::Collections::IEnumerable c)
References LlamaLibrary.StringsAndFloats.Add().
StringsAndFloats() [3/6]
LlamaLibrary.StringsAndFloats.StringsAndFloats (global::System::Collections::Generic::IEnumerable< StringAndFloat > c)
References LlamaLibrary.StringsAndFloats.Add().
StringsAndFloats() [4/6]
LlamaLibrary.StringsAndFloats.StringsAndFloats ()
Referenced by LlamaLibrary.StringsAndFloats.GetRange(), and LlamaLibrary.StringsAndFloats.Repeat().
StringsAndFloats() [5/6]
LlamaLibrary.StringsAndFloats.StringsAndFloats (StringsAndFloats other)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
StringsAndFloats() [6/6]
LlamaLibrary.StringsAndFloats.StringsAndFloats (int capacity)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Member Function Documentation
Add()
void LlamaLibrary.StringsAndFloats.Add (StringAndFloat x)
References LlamaLibrary.StringAndFloat.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Add(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Referenced by LlamaLibrary.StringsAndFloats.StringsAndFloats(), and LlamaLibrary.StringsAndFloats.StringsAndFloats().
AddRange()
void LlamaLibrary.StringsAndFloats.AddRange (StringsAndFloats values)
References LlamaLibrary.StringsAndFloats.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_AddRange(), and LlamaLibrary.StringsAndFloats.swigCPtr.
capacity()
uint LlamaLibrary.StringsAndFloats.capacity () private
References LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_capacity(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Clear()
void LlamaLibrary.StringsAndFloats.Clear ()
References LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Clear(), and LlamaLibrary.StringsAndFloats.swigCPtr.
CopyTo() [1/3]
void LlamaLibrary.StringsAndFloats.CopyTo (int index, StringAndFloat[] array, int arrayIndex, int count)
References LlamaLibrary.StringsAndFloats.Count, and LlamaLibrary.StringsAndFloats.getitemcopy().
CopyTo() [2/3]
void LlamaLibrary.StringsAndFloats.CopyTo (StringAndFloat[] array)
References LlamaLibrary.StringsAndFloats.CopyTo(), and LlamaLibrary.StringsAndFloats.Count.
Referenced by LlamaLibrary.StringsAndFloats.CopyTo(), LlamaLibrary.StringsAndFloats.CopyTo(), and LlamaLibrary.StringsAndFloats.ToArray().
CopyTo() [3/3]
void LlamaLibrary.StringsAndFloats.CopyTo (StringAndFloat[] array, int arrayIndex)
References LlamaLibrary.StringsAndFloats.CopyTo(), and LlamaLibrary.StringsAndFloats.Count.
Dispose()
virtual void LlamaLibrary.StringsAndFloats.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_StringsAndFloats(), LlamaLibrary.StringsAndFloats.swigCMemOwn, and LlamaLibrary.StringsAndFloats.swigCPtr.
Referenced by LlamaLibrary.StringsAndFloats.~StringsAndFloats().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.StringsAndFloats.getCPtr (StringsAndFloats obj) static package
References LlamaLibrary.StringsAndFloats.swigCPtr.
Referenced by LlamaLibrary.StringsAndFloats.AddRange(), LlamaLibrary.StringsAndFloats.InsertRange(), and LlamaLibrary.StringsAndFloats.SetRange().
GetEnumerator() [1/3]
global.System.Collections.Generic.IEnumerator< StringAndFloat > global.System.Collections.Generic.IEnumerable< StringAndFloat >. LlamaLibrary.StringsAndFloats.GetEnumerator () private
GetEnumerator() [2/3]
global.System.Collections.IEnumerator global.System.Collections.IEnumerable. LlamaLibrary.StringsAndFloats.GetEnumerator () private
GetEnumerator() [3/3]
StringsAndFloatsEnumerator LlamaLibrary.StringsAndFloats.GetEnumerator ()
getitem()
StringAndFloat LlamaLibrary.StringsAndFloats.getitem (int index) private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_getitem(), and LlamaLibrary.StringsAndFloats.swigCPtr.
getitemcopy()
StringAndFloat LlamaLibrary.StringsAndFloats.getitemcopy (int index) private
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_getitemcopy(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Referenced by LlamaLibrary.StringsAndFloats.CopyTo().
GetRange()
StringsAndFloats LlamaLibrary.StringsAndFloats.GetRange (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.StringsAndFloats.StringsAndFloats(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_GetRange(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Insert()
void LlamaLibrary.StringsAndFloats.Insert (int index, StringAndFloat x)
References LlamaLibrary.StringAndFloat.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Insert(), and LlamaLibrary.StringsAndFloats.swigCPtr.
InsertRange()
void LlamaLibrary.StringsAndFloats.InsertRange (int index, StringsAndFloats values)
References LlamaLibrary.StringsAndFloats.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_InsertRange(), and LlamaLibrary.StringsAndFloats.swigCPtr.
RemoveAt()
void LlamaLibrary.StringsAndFloats.RemoveAt (int index)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_RemoveAt(), and LlamaLibrary.StringsAndFloats.swigCPtr.
RemoveRange()
void LlamaLibrary.StringsAndFloats.RemoveRange (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_RemoveRange(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Repeat()
static StringsAndFloats LlamaLibrary.StringsAndFloats.Repeat (StringAndFloat value, int count) static
References LlamaLibrary.StringAndFloat.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.StringsAndFloats.StringsAndFloats(), and LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Repeat().
reserve()
void LlamaLibrary.StringsAndFloats.reserve (uint n) private
References LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_reserve(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Reverse() [1/2]
void LlamaLibrary.StringsAndFloats.Reverse ()
References LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Reverse__SWIG_0(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Reverse() [2/2]
void LlamaLibrary.StringsAndFloats.Reverse (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_Reverse__SWIG_1(), and LlamaLibrary.StringsAndFloats.swigCPtr.
setitem()
void LlamaLibrary.StringsAndFloats.setitem (int index, StringAndFloat value) private
References LlamaLibrary.StringAndFloat.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_setitem(), and LlamaLibrary.StringsAndFloats.swigCPtr.
SetRange()
void LlamaLibrary.StringsAndFloats.SetRange (int index, StringsAndFloats values)
References LlamaLibrary.StringsAndFloats.getCPtr(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_SetRange(), and LlamaLibrary.StringsAndFloats.swigCPtr.
size()
uint LlamaLibrary.StringsAndFloats.size () private
References LlamaLibrary.libllama_libPINVOKE.StringsAndFloats_size(), and LlamaLibrary.StringsAndFloats.swigCPtr.
Referenced by LlamaLibrary.StringsAndFloats.StringsAndFloatsEnumerator.MoveNext().
ToArray()
StringAndFloat[] LlamaLibrary.StringsAndFloats.ToArray ()
References LlamaLibrary.StringsAndFloats.CopyTo(), and LlamaLibrary.StringsAndFloats.Count.
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.StringsAndFloats.swigCMemOwn protected
Referenced by LlamaLibrary.StringsAndFloats.Dispose(), and LlamaLibrary.StringsAndFloats.StringsAndFloats().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.StringsAndFloats.swigCPtr private
Referenced by LlamaLibrary.StringsAndFloats.Add(), LlamaLibrary.StringsAndFloats.AddRange(), LlamaLibrary.StringsAndFloats.capacity(), LlamaLibrary.StringsAndFloats.Clear(), LlamaLibrary.StringsAndFloats.Dispose(), LlamaLibrary.StringsAndFloats.getCPtr(), LlamaLibrary.StringsAndFloats.getitem(), LlamaLibrary.StringsAndFloats.getitemcopy(), LlamaLibrary.StringsAndFloats.GetRange(), LlamaLibrary.StringsAndFloats.Insert(), LlamaLibrary.StringsAndFloats.InsertRange(), LlamaLibrary.StringsAndFloats.RemoveAt(), LlamaLibrary.StringsAndFloats.RemoveRange(), LlamaLibrary.StringsAndFloats.reserve(), LlamaLibrary.StringsAndFloats.Reverse(), LlamaLibrary.StringsAndFloats.Reverse(), LlamaLibrary.StringsAndFloats.setitem(), LlamaLibrary.StringsAndFloats.SetRange(), LlamaLibrary.StringsAndFloats.size(), and LlamaLibrary.StringsAndFloats.StringsAndFloats().
Property Documentation
Capacity
int LlamaLibrary.StringsAndFloats.Capacity get set
Count
int LlamaLibrary.StringsAndFloats.Count get
Referenced by LlamaLibrary.StringsAndFloats.CopyTo(), LlamaLibrary.StringsAndFloats.CopyTo(), LlamaLibrary.StringsAndFloats.CopyTo(), LlamaLibrary.StringsAndFloats.StringsAndFloatsEnumerator.MoveNext(), LlamaLibrary.StringsAndFloats.StringsAndFloatsEnumerator.Reset(), LlamaLibrary.StringsAndFloats.StringsAndFloatsEnumerator.StringsAndFloatsEnumerator(), and LlamaLibrary.StringsAndFloats.ToArray().
IsFixedSize
bool LlamaLibrary.StringsAndFloats.IsFixedSize get
IsReadOnly
bool LlamaLibrary.StringsAndFloats.IsReadOnly get
IsSynchronized
bool LlamaLibrary.StringsAndFloats.IsSynchronized get
this[int index]
StringAndFloat LlamaLibrary.StringsAndFloats.this[int index] get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/StringsAndFloats.cs