StyledLines from testedlines.com: C# docs: LlamaLibrary.FileWrapper Class Reference
LlamaLibrary.FileWrapper Class Reference
Public Member Functions
virtual void Dispose ()
FileWrapper ()
Static Public Member Functions
static bool Save (byte[] data, int data_length, string path)
static bool Save (string data, string path)
static bool Save (string data, uint data_length, string path)
Protected Attributes
bool swigCMemOwn
Package Functions
FileWrapper (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (FileWrapper obj)
Private Member Functions
~FileWrapper ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
FileWrapper() [1/2]
LlamaLibrary.FileWrapper.FileWrapper (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.FileWrapper.swigCMemOwn, and LlamaLibrary.FileWrapper.swigCPtr.
~FileWrapper()
LlamaLibrary.FileWrapper.~FileWrapper () private
References LlamaLibrary.FileWrapper.Dispose().
FileWrapper() [2/2]
LlamaLibrary.FileWrapper.FileWrapper ()
Member Function Documentation
Dispose()
virtual void LlamaLibrary.FileWrapper.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_FileWrapper(), LlamaLibrary.FileWrapper.swigCMemOwn, and LlamaLibrary.FileWrapper.swigCPtr.
Referenced by LlamaLibrary.FileWrapper.~FileWrapper().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.FileWrapper.getCPtr (FileWrapper obj) static package
References LlamaLibrary.FileWrapper.swigCPtr.
Save() [1/3]
static bool LlamaLibrary.FileWrapper.Save (byte[] data, int data_length, string path) static
References LlamaLibrary.libllama_libPINVOKE.FileWrapper_Save__SWIG_1(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Save() [2/3]
static bool LlamaLibrary.FileWrapper.Save (string data, string path) static
References LlamaLibrary.libllama_libPINVOKE.FileWrapper_Save__SWIG_0(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.ModelController.ModelController(), and Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.Start().
Save() [3/3]
static bool LlamaLibrary.FileWrapper.Save (string data, uint data_length, string path) static
References LlamaLibrary.libllama_libPINVOKE.FileWrapper_Save__SWIG_2(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.FileWrapper.swigCMemOwn protected
Referenced by LlamaLibrary.FileWrapper.Dispose(), and LlamaLibrary.FileWrapper.FileWrapper().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.FileWrapper.swigCPtr private
Referenced by LlamaLibrary.FileWrapper.Dispose(), LlamaLibrary.FileWrapper.FileWrapper(), and LlamaLibrary.FileWrapper.getCPtr().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/FileWrapper.cs