StyledLines from testedlines.com: C# docs: LlamaLibrary.CallbackWrapper Class Reference
LlamaLibrary.CallbackWrapper Class Reference
Static Public Member Functions
static void RegisterCompletionCallback (LoggingContext model, Action< LlamaInfrence, string, string > callback)
Registers a completion callback function for the Llama model.
static void RegisterLogCallback (LoggingContext model, Action< LlamaInfrence, string > callback)
Registers a log callback function for the Llama model.
static void RegisterTokenCallback (LoggingContext model, Action< LlamaInfrence, string > callback)
Registers a token callback function for the Llama model.
Static Public Attributes
const string LIBRARY_NAME = "libllama_lib"
Specifies the name of the native library based on the platform.
Private Member Functions
delegate void CompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length)
Delegate for handling completion callback functions from the native library.
delegate void LogCallback (IntPtr ctx, IntPtr message, int length)
Delegate for handling log callback functions from the native library.
static void SetCompletionCallback (IntPtr ctx, CompleteCallback callback)
Sets the completion callback function for the native library.
static void SetLogCallback (IntPtr ctx, LogCallback callback)
Sets the log callback function for the native library.
static void SetTokenCallback (IntPtr ctx, TokenCallback callback)
Sets the token callback function for the native library.
delegate void TokenCallback (IntPtr ctx, IntPtr message, int length)
Delegate for handling token callback functions from the native library.
Static Private Member Functions
static void StaticCompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length)
Static method to handle the completion callback from the native library.
static void StaticLogCallback (IntPtr ctx, IntPtr message, int length)
Static method to handle the log callback from the native library.
static void StaticTokenCallback (IntPtr ctx, IntPtr message, int length)
Static method to handle the token callback from the native library.
Static Private Attributes
static Action< LlamaInfrence, string, string > completionCallbackAction
Stores the action to be executed when the completion callback is triggered.
static Action< LlamaInfrence, string > logCallbackAction
Stores the action to be executed when the log callback is triggered.
static Action< LlamaInfrence, string > tokenCallbackAction
Stores the action to be executed when the token callback is triggered.
Member Function Documentation
CompleteCallback()
delegate void LlamaLibrary.CallbackWrapper.CompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length) private
Delegate for handling completion callback functions from the native library.
LogCallback()
delegate void LlamaLibrary.CallbackWrapper.LogCallback (IntPtr ctx, IntPtr message, int length) private
Delegate for handling log callback functions from the native library.
RegisterCompletionCallback()
static void LlamaLibrary.CallbackWrapper.RegisterCompletionCallback (LoggingContext model, Action< LlamaInfrence, string, string > callback) static
Registers a completion callback function for the Llama model.
Parameters
model The logging context of the Llama model.
callback The action to be executed on completion callback.
References LlamaLibrary.CallbackWrapper.completionCallbackAction, LlamaLibrary.CallbackWrapper.SetCompletionCallback(), LlamaLibrary.CallbackWrapper.StaticCompleteCallback(), and LlamaLibrary.LoggingContext.swigCPtr.
Referenced by RunModelAsync.Start().
RegisterLogCallback()
static void LlamaLibrary.CallbackWrapper.RegisterLogCallback (LoggingContext model, Action< LlamaInfrence, string > callback) static
Registers a log callback function for the Llama model.
Parameters
model The logging context of the Llama model.
callback The action to be executed on log callback.
References LlamaLibrary.CallbackWrapper.logCallbackAction, LlamaLibrary.CallbackWrapper.SetLogCallback(), LlamaLibrary.CallbackWrapper.StaticLogCallback(), and LlamaLibrary.LoggingContext.swigCPtr.
Referenced by RunModelAsync.Start().
RegisterTokenCallback()
static void LlamaLibrary.CallbackWrapper.RegisterTokenCallback (LoggingContext model, Action< LlamaInfrence, string > callback) static
Registers a token callback function for the Llama model.
Parameters
model The logging context of the Llama model.
callback The action to be executed on token callback.
References LlamaLibrary.CallbackWrapper.SetTokenCallback(), LlamaLibrary.CallbackWrapper.StaticTokenCallback(), LlamaLibrary.LoggingContext.swigCPtr, and LlamaLibrary.CallbackWrapper.tokenCallbackAction.
Referenced by ModelController.ModelController(), and RunModelAsync.Start().
SetCompletionCallback()
static void LlamaLibrary.CallbackWrapper.SetCompletionCallback (IntPtr ctx, CompleteCallback callback) private
Sets the completion callback function for the native library.
Parameters
ctx The context pointer.
callback The callback function to register.
Referenced by LlamaLibrary.CallbackWrapper.RegisterCompletionCallback().
SetLogCallback()
static void LlamaLibrary.CallbackWrapper.SetLogCallback (IntPtr ctx, LogCallback callback) private
Sets the log callback function for the native library.
Parameters
ctx The context pointer.
callback The callback function to register.
Referenced by LlamaLibrary.CallbackWrapper.RegisterLogCallback().
SetTokenCallback()
static void LlamaLibrary.CallbackWrapper.SetTokenCallback (IntPtr ctx, TokenCallback callback) private
Sets the token callback function for the native library.
Parameters
ctx The context pointer.
callback The callback function to register.
Referenced by LlamaLibrary.CallbackWrapper.RegisterTokenCallback().
StaticCompleteCallback()
static void LlamaLibrary.CallbackWrapper.StaticCompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length) static private
Static method to handle the completion callback from the native library.
Parameters
ctx The context pointer.
input_message The input message pointer.
input_length The length of the input message.
output_message The output message pointer.
output_length The length of the output message.
References LlamaLibrary.CallbackWrapper.completionCallbackAction.
Referenced by LlamaLibrary.CallbackWrapper.RegisterCompletionCallback().
StaticLogCallback()
static void LlamaLibrary.CallbackWrapper.StaticLogCallback (IntPtr ctx, IntPtr message, int length) static private
Static method to handle the log callback from the native library.
Parameters
ctx The context pointer.
message The message pointer.
length The length of the message.
References LlamaLibrary.CallbackWrapper.logCallbackAction.
Referenced by LlamaLibrary.CallbackWrapper.RegisterLogCallback().
StaticTokenCallback()
static void LlamaLibrary.CallbackWrapper.StaticTokenCallback (IntPtr ctx, IntPtr message, int length) static private
Static method to handle the token callback from the native library.
Parameters
ctx The context pointer.
message The message pointer.
length The length of the message.
References LlamaLibrary.CallbackWrapper.tokenCallbackAction.
Referenced by LlamaLibrary.CallbackWrapper.RegisterTokenCallback().
TokenCallback()
delegate void LlamaLibrary.CallbackWrapper.TokenCallback (IntPtr ctx, IntPtr message, int length) private
Delegate for handling token callback functions from the native library.
Member Data Documentation
completionCallbackAction
Action<LlamaInfrence, string, string> LlamaLibrary.CallbackWrapper.completionCallbackAction static private
Stores the action to be executed when the completion callback is triggered.
Referenced by LlamaLibrary.CallbackWrapper.RegisterCompletionCallback(), and LlamaLibrary.CallbackWrapper.StaticCompleteCallback().
LIBRARY_NAME
const string LlamaLibrary.CallbackWrapper.LIBRARY_NAME = "libllama_lib" static
Specifies the name of the native library based on the platform.
logCallbackAction
Action<LlamaInfrence, string> LlamaLibrary.CallbackWrapper.logCallbackAction static private
Stores the action to be executed when the log callback is triggered.
Referenced by LlamaLibrary.CallbackWrapper.RegisterLogCallback(), and LlamaLibrary.CallbackWrapper.StaticLogCallback().
tokenCallbackAction
Action<LlamaInfrence, string> LlamaLibrary.CallbackWrapper.tokenCallbackAction static private
Stores the action to be executed when the token callback is triggered.
Referenced by LlamaLibrary.CallbackWrapper.RegisterTokenCallback(), and LlamaLibrary.CallbackWrapper.StaticTokenCallback().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/CallbackWrapper.cs