StyledLines from testedlines.com: C# docs: LlamaLibrary.LoggingContext Class Reference
LlamaLibrary.LoggingContext Class Reference
Public Member Functions
virtual void Dispose ()
LoggingContext ()
Public Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Protected Attributes
bool swigCMemOwn
Package Functions
LoggingContext (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (LoggingContext obj)
Properties
SWIGTYPE_p_LoggingContext__LoggingContextPimpl pImpl [get, set]
Private Member Functions
~LoggingContext ()
Constructor & Destructor Documentation
LoggingContext() [1/2]
LlamaLibrary.LoggingContext.LoggingContext (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.LoggingContext.swigCMemOwn, and LlamaLibrary.LoggingContext.swigCPtr.
~LoggingContext()
LlamaLibrary.LoggingContext.~LoggingContext () private
References LlamaLibrary.LoggingContext.Dispose().
LoggingContext() [2/2]
LlamaLibrary.LoggingContext.LoggingContext ()
Member Function Documentation
Dispose()
virtual void LlamaLibrary.LoggingContext.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_LoggingContext(), LlamaLibrary.LoggingContext.swigCMemOwn, and LlamaLibrary.LoggingContext.swigCPtr.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnDestroy(), and LlamaLibrary.LoggingContext.~LoggingContext().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.LoggingContext.getCPtr (LoggingContext obj) static package
References LlamaLibrary.LoggingContext.swigCPtr.
Referenced by LlamaLibrary.AsyncLlamaInfrence.SetupAsync().
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.LoggingContext.swigCMemOwn protected
Referenced by LlamaLibrary.LoggingContext.Dispose(), and LlamaLibrary.LoggingContext.LoggingContext().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.LoggingContext.swigCPtr
Referenced by LlamaLibrary.LoggingContext.Dispose(), LlamaLibrary.LoggingContext.getCPtr(), LlamaLibrary.LoggingContext.LoggingContext(), Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterCompletionCallback(), Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterLogCallback(), and Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterTokenCallback().
Property Documentation
pImpl
SWIGTYPE_p_LoggingContext__LoggingContextPimpl LlamaLibrary.LoggingContext.pImpl get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/LoggingContext.cs