StyledLines from testedlines.com: C# docs: DisableWhileNotConfigured Class Reference
DisableWhileNotConfigured Class Reference
Public Attributes
RunModelAsync StateController
List< Selectable > UiObjects
Private Member Functions
void OnDestroy ()
void OnStateChanged (RunModelAsync.State state)
void SetUIObjectsActive (bool isActive)
void Start ()
Member Function Documentation
OnDestroy()
void DisableWhileNotConfigured.OnDestroy () private
References RunModelAsync.OnStateChanged, OnStateChanged(), and StateController.
OnStateChanged()
void DisableWhileNotConfigured.OnStateChanged (RunModelAsync::State state) private
References SetUIObjectsActive().
Referenced by OnDestroy(), and Start().
SetUIObjectsActive()
void DisableWhileNotConfigured.SetUIObjectsActive (bool isActive) private
References UiObjects.
Referenced by OnStateChanged(), and Start().
Start()
void DisableWhileNotConfigured.Start () private
References RunModelAsync.OnStateChanged, OnStateChanged(), SetUIObjectsActive(), and StateController.
Member Data Documentation
StateController
RunModelAsync DisableWhileNotConfigured.StateController
Referenced by OnDestroy(), and Start().
UiObjects
List<Selectable> DisableWhileNotConfigured.UiObjects
Referenced by SetUIObjectsActive().
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/DisableWhileNotConfigured.cs