StyledLines from testedlines.com: C# docs: PrintModelState Class Reference
PrintModelState Class Reference
Public Attributes
RunModelAsync StateController
TMP_Text UiObject
Private Member Functions
void OnDestroy ()
void OnStateChanged (RunModelAsync.State state)
void Start ()
Member Function Documentation
OnDestroy()
void PrintModelState.OnDestroy () private
References RunModelAsync.OnStateChanged, OnStateChanged(), and StateController.
OnStateChanged()
void PrintModelState.OnStateChanged (RunModelAsync::State state) private
Referenced by OnDestroy(), and Start().
Start()
void PrintModelState.Start () private
References RunModelAsync.OnStateChanged, OnStateChanged(), and StateController.
Member Data Documentation
StateController
RunModelAsync PrintModelState.StateController
Referenced by OnDestroy(), and Start().
UiObject
TMP_Text PrintModelState.UiObject
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/PrintModelState.cs