StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore Class Reference
Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore Class Reference
Public Attributes
RunModelAsync StateController
TMP_Text UiObject
Private Member Functions
void OnDestroy ()
void OnStateChangedDone (string text)
void OnStateChangedStart (string text)
void Start ()
Member Function Documentation
OnDestroy()
void Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnDestroy () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedComplete, Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedOutputChanged, Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnStateChangedDone(), Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnStateChangedStart(), and Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.StateController.
OnStateChangedDone()
void Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnStateChangedDone (string text) private
Referenced by Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.Start().
OnStateChangedStart()
void Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnStateChangedStart (string text) private
Referenced by Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.Start().
Start()
void Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.Start () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedComplete, Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnGeneratedOutputChanged, Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnStateChangedDone(), Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnStateChangedStart(), and Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.StateController.
Member Data Documentation
StateController
RunModelAsync Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.StateController
Referenced by Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.Start().
UiObject
TMP_Text Assets.StyledLines.Runtime.UIHelpers.PrintStopwatchScore.UiObject
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/PrintStopwatchScore.cs