StyledLines from testedlines.com: C# docs: LlamaLibrary.LlamaControlVectorLoadInfos Class Reference
LlamaLibrary.LlamaControlVectorLoadInfos Class Reference
Classes
class LlamaControlVectorLoadInfosEnumerator
Public Member Functions
void Add (SWIGTYPE_p_llama_control_vector_load_info x)
void AddRange (LlamaControlVectorLoadInfos values)
void Clear ()
void CopyTo (int index, SWIGTYPE_p_llama_control_vector_load_info[] array, int arrayIndex, int count)
void CopyTo (SWIGTYPE_p_llama_control_vector_load_info[] array)
void CopyTo (SWIGTYPE_p_llama_control_vector_load_info[] array, int arrayIndex)
virtual void Dispose ()
LlamaControlVectorLoadInfosEnumerator GetEnumerator ()
LlamaControlVectorLoadInfos GetRange (int index, int count)
void Insert (int index, SWIGTYPE_p_llama_control_vector_load_info x)
void InsertRange (int index, LlamaControlVectorLoadInfos values)
LlamaControlVectorLoadInfos ()
LlamaControlVectorLoadInfos (global::System.Collections.Generic.IEnumerable< SWIGTYPE_p_llama_control_vector_load_info > c)
LlamaControlVectorLoadInfos (global::System.Collections.IEnumerable c)
LlamaControlVectorLoadInfos (int capacity)
LlamaControlVectorLoadInfos (LlamaControlVectorLoadInfos other)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, LlamaControlVectorLoadInfos values)
SWIGTYPE_p_llama_control_vector_load_info[] ToArray ()
Static Public Member Functions
static LlamaControlVectorLoadInfos Repeat (SWIGTYPE_p_llama_control_vector_load_info value, int count)
Protected Attributes
bool swigCMemOwn
Package Functions
LlamaControlVectorLoadInfos (global::System.IntPtr cPtr, bool cMemoryOwn)
Static Package Functions
static global::System.Runtime.InteropServices.HandleRef getCPtr (LlamaControlVectorLoadInfos obj)
Properties
int Capacity [get, set]
int Count [get]
bool IsFixedSize [get]
bool IsReadOnly [get]
bool IsSynchronized [get]
SWIGTYPE_p_llama_control_vector_load_info this[int index] [get, set]
Private Member Functions
uint capacity ()
global::System.Collections.Generic.IEnumerator< SWIGTYPE_p_llama_control_vector_load_info > global::System.Collections.Generic.IEnumerable< SWIGTYPE_p_llama_control_vector_load_info >. GetEnumerator ()
global::System.Collections.IEnumerator global::System.Collections.IEnumerable. GetEnumerator ()
SWIGTYPE_p_llama_control_vector_load_info getitem (int index)
SWIGTYPE_p_llama_control_vector_load_info getitemcopy (int index)
void reserve (uint n)
void setitem (int index, SWIGTYPE_p_llama_control_vector_load_info value)
uint size ()
~LlamaControlVectorLoadInfos ()
Private Attributes
global::System.Runtime.InteropServices.HandleRef swigCPtr
Constructor & Destructor Documentation
LlamaControlVectorLoadInfos() [1/6]
LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos (global::System::IntPtr cPtr, bool cMemoryOwn) package
References LlamaLibrary.LlamaControlVectorLoadInfos.swigCMemOwn, and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
~LlamaControlVectorLoadInfos()
LlamaLibrary.LlamaControlVectorLoadInfos.~LlamaControlVectorLoadInfos () private
References LlamaLibrary.LlamaControlVectorLoadInfos.Dispose().
LlamaControlVectorLoadInfos() [2/6]
LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos (global::System::Collections::IEnumerable c)
References LlamaLibrary.LlamaControlVectorLoadInfos.Add().
LlamaControlVectorLoadInfos() [3/6]
LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos (global::System::Collections::Generic::IEnumerable< SWIGTYPE_p_llama_control_vector_load_info > c)
References LlamaLibrary.LlamaControlVectorLoadInfos.Add().
LlamaControlVectorLoadInfos() [4/6]
LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos ()
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.GetRange(), and LlamaLibrary.LlamaControlVectorLoadInfos.Repeat().
LlamaControlVectorLoadInfos() [5/6]
LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos (LlamaControlVectorLoadInfos other)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
LlamaControlVectorLoadInfos() [6/6]
LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos (int capacity)
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
Member Function Documentation
Add()
void LlamaLibrary.LlamaControlVectorLoadInfos.Add (SWIGTYPE_p_llama_control_vector_load_info x)
References LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.getCPtr(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Add(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), and LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos().
AddRange()
void LlamaLibrary.LlamaControlVectorLoadInfos.AddRange (LlamaControlVectorLoadInfos values)
References LlamaLibrary.LlamaControlVectorLoadInfos.getCPtr(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_AddRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
capacity()
uint LlamaLibrary.LlamaControlVectorLoadInfos.capacity () private
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_capacity(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Clear()
void LlamaLibrary.LlamaControlVectorLoadInfos.Clear ()
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Clear(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
CopyTo() [1/3]
void LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo (int index, SWIGTYPE_p_llama_control_vector_load_info[] array, int arrayIndex, int count)
References LlamaLibrary.LlamaControlVectorLoadInfos.Count, and LlamaLibrary.LlamaControlVectorLoadInfos.getitemcopy().
CopyTo() [2/3]
void LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo (SWIGTYPE_p_llama_control_vector_load_info[] array)
References LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), and LlamaLibrary.LlamaControlVectorLoadInfos.Count.
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), and LlamaLibrary.LlamaControlVectorLoadInfos.ToArray().
CopyTo() [3/3]
void LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo (SWIGTYPE_p_llama_control_vector_load_info[] array, int arrayIndex)
References LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), and LlamaLibrary.LlamaControlVectorLoadInfos.Count.
Dispose()
virtual void LlamaLibrary.LlamaControlVectorLoadInfos.Dispose () virtual
References LlamaLibrary.libllama_libPINVOKE.delete_LlamaControlVectorLoadInfos(), LlamaLibrary.LlamaControlVectorLoadInfos.swigCMemOwn, and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.~LlamaControlVectorLoadInfos().
getCPtr()
static global.System.Runtime.InteropServices.HandleRef LlamaLibrary.LlamaControlVectorLoadInfos.getCPtr (LlamaControlVectorLoadInfos obj) static package
References LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.AddRange(), LlamaLibrary.LlamaControlVectorLoadInfos.InsertRange(), and LlamaLibrary.LlamaControlVectorLoadInfos.SetRange().
GetEnumerator() [1/3]
global.System.Collections.Generic.IEnumerator< SWIGTYPE_p_llama_control_vector_load_info > global.System.Collections.Generic.IEnumerable< SWIGTYPE_p_llama_control_vector_load_info >. LlamaLibrary.LlamaControlVectorLoadInfos.GetEnumerator () private
GetEnumerator() [2/3]
global.System.Collections.IEnumerator global.System.Collections.IEnumerable. LlamaLibrary.LlamaControlVectorLoadInfos.GetEnumerator () private
GetEnumerator() [3/3]
LlamaControlVectorLoadInfosEnumerator LlamaLibrary.LlamaControlVectorLoadInfos.GetEnumerator ()
getitem()
SWIGTYPE_p_llama_control_vector_load_info LlamaLibrary.LlamaControlVectorLoadInfos.getitem (int index) private
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_getitem(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
getitemcopy()
SWIGTYPE_p_llama_control_vector_load_info LlamaLibrary.LlamaControlVectorLoadInfos.getitemcopy (int index) private
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_getitemcopy(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo().
GetRange()
LlamaControlVectorLoadInfos LlamaLibrary.LlamaControlVectorLoadInfos.GetRange (int index, int count)
References LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_GetRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Insert()
void LlamaLibrary.LlamaControlVectorLoadInfos.Insert (int index, SWIGTYPE_p_llama_control_vector_load_info x)
References LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.getCPtr(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Insert(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
InsertRange()
void LlamaLibrary.LlamaControlVectorLoadInfos.InsertRange (int index, LlamaControlVectorLoadInfos values)
References LlamaLibrary.LlamaControlVectorLoadInfos.getCPtr(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_InsertRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
RemoveAt()
void LlamaLibrary.LlamaControlVectorLoadInfos.RemoveAt (int index)
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_RemoveAt(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
RemoveRange()
void LlamaLibrary.LlamaControlVectorLoadInfos.RemoveRange (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_RemoveRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Repeat()
static LlamaControlVectorLoadInfos LlamaLibrary.LlamaControlVectorLoadInfos.Repeat (SWIGTYPE_p_llama_control_vector_load_info value, int count) static
References LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.getCPtr(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Repeat(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve().
reserve()
void LlamaLibrary.LlamaControlVectorLoadInfos.reserve (uint n) private
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_reserve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Reverse() [1/2]
void LlamaLibrary.LlamaControlVectorLoadInfos.Reverse ()
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Reverse__SWIG_0(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Reverse() [2/2]
void LlamaLibrary.LlamaControlVectorLoadInfos.Reverse (int index, int count)
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_Reverse__SWIG_1(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
setitem()
void LlamaLibrary.LlamaControlVectorLoadInfos.setitem (int index, SWIGTYPE_p_llama_control_vector_load_info value) private
References LlamaLibrary.SWIGTYPE_p_llama_control_vector_load_info.getCPtr(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_setitem(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
SetRange()
void LlamaLibrary.LlamaControlVectorLoadInfos.SetRange (int index, LlamaControlVectorLoadInfos values)
References LlamaLibrary.LlamaControlVectorLoadInfos.getCPtr(), LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_SetRange(), LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending, LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
size()
uint LlamaLibrary.LlamaControlVectorLoadInfos.size () private
References LlamaLibrary.libllama_libPINVOKE.LlamaControlVectorLoadInfos_size(), and LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr.
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfosEnumerator.MoveNext().
ToArray()
SWIGTYPE_p_llama_control_vector_load_info[] LlamaLibrary.LlamaControlVectorLoadInfos.ToArray ()
References LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), and LlamaLibrary.LlamaControlVectorLoadInfos.Count.
Member Data Documentation
swigCMemOwn
bool LlamaLibrary.LlamaControlVectorLoadInfos.swigCMemOwn protected
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Dispose(), and LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos().
swigCPtr
global.System.Runtime.InteropServices.HandleRef LlamaLibrary.LlamaControlVectorLoadInfos.swigCPtr private
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.Add(), LlamaLibrary.LlamaControlVectorLoadInfos.AddRange(), LlamaLibrary.LlamaControlVectorLoadInfos.capacity(), LlamaLibrary.LlamaControlVectorLoadInfos.Clear(), LlamaLibrary.LlamaControlVectorLoadInfos.Dispose(), LlamaLibrary.LlamaControlVectorLoadInfos.getCPtr(), LlamaLibrary.LlamaControlVectorLoadInfos.getitem(), LlamaLibrary.LlamaControlVectorLoadInfos.getitemcopy(), LlamaLibrary.LlamaControlVectorLoadInfos.GetRange(), LlamaLibrary.LlamaControlVectorLoadInfos.Insert(), LlamaLibrary.LlamaControlVectorLoadInfos.InsertRange(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), LlamaLibrary.LlamaControlVectorLoadInfos.RemoveAt(), LlamaLibrary.LlamaControlVectorLoadInfos.RemoveRange(), LlamaLibrary.LlamaControlVectorLoadInfos.reserve(), LlamaLibrary.LlamaControlVectorLoadInfos.Reverse(), LlamaLibrary.LlamaControlVectorLoadInfos.Reverse(), LlamaLibrary.LlamaControlVectorLoadInfos.setitem(), LlamaLibrary.LlamaControlVectorLoadInfos.SetRange(), and LlamaLibrary.LlamaControlVectorLoadInfos.size().
Property Documentation
Capacity
int LlamaLibrary.LlamaControlVectorLoadInfos.Capacity get set
Count
int LlamaLibrary.LlamaControlVectorLoadInfos.Count get
Referenced by LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), LlamaLibrary.LlamaControlVectorLoadInfos.CopyTo(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfosEnumerator.LlamaControlVectorLoadInfosEnumerator(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfosEnumerator.MoveNext(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfosEnumerator.Reset(), and LlamaLibrary.LlamaControlVectorLoadInfos.ToArray().
IsFixedSize
bool LlamaLibrary.LlamaControlVectorLoadInfos.IsFixedSize get
IsReadOnly
bool LlamaLibrary.LlamaControlVectorLoadInfos.IsReadOnly get
IsSynchronized
bool LlamaLibrary.LlamaControlVectorLoadInfos.IsSynchronized get
this[int index]
SWIGTYPE_p_llama_control_vector_load_info LlamaLibrary.LlamaControlVectorLoadInfos.this[int index] get set
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/LlamaControlVectorLoadInfos.cs