StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper Class Reference
Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper Class Reference
Static Public Member Functions
static void RegisterCompletionCallback (LoggingContext model, Action< LlamaLibrary.LlamaInfrence, string, string > callback)
Registers a completion callback function for the Llama model.
static void RegisterLogCallback (LoggingContext model, Action< LlamaLibrary.LlamaInfrence, string > callback)
Registers a log callback function for the Llama model.
static void RegisterTokenCallback (LoggingContext model, Action< LlamaLibrary.LlamaInfrence, string > callback)
Registers a token callback function for the Llama model.
Static Public Attributes
const string LIBRARY_NAME = "libllama_lib"
Specifies the name of the native library based on the platform.
Private Member Functions
delegate void CompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length)
Delegate for handling completion callback functions from the native library.
delegate void LogCallback (IntPtr ctx, IntPtr message, int length)
Delegate for handling log callback functions from the native library.
static void SetCompletionCallback (IntPtr ctx, CompleteCallback callback)
Sets the completion callback function for the native library.
static void SetLogCallback (IntPtr ctx, LogCallback callback)
Sets the log callback function for the native library.
static void SetTokenCallback (IntPtr ctx, TokenCallback callback)
Sets the token callback function for the native library.
delegate void TokenCallback (IntPtr ctx, IntPtr message, int length)
Delegate for handling token callback functions from the native library.
Static Private Member Functions
static void StaticCompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length)
Static method to handle the completion callback from the native library.
static void StaticLogCallback (IntPtr ctx, IntPtr message, int length)
Static method to handle the log callback from the native library.
static void StaticTokenCallback (IntPtr ctx, IntPtr message, int length)
Static method to handle the token callback from the native library.
Static Private Attributes
static Action< LlamaLibrary.LlamaInfrence, string, string > completionCallbackAction
Stores the action to be executed when the completion callback is triggered.
static Action< LlamaLibrary.LlamaInfrence, string > logCallbackAction
Stores the action to be executed when the log callback is triggered.
static Action< LlamaLibrary.LlamaInfrence, string > tokenCallbackAction
Stores the action to be executed when the token callback is triggered.
Member Function Documentation
CompleteCallback()
delegate void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.CompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length) private
Delegate for handling completion callback functions from the native library.
LogCallback()
delegate void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.LogCallback (IntPtr ctx, IntPtr message, int length) private
Delegate for handling log callback functions from the native library.
RegisterCompletionCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterCompletionCallback (LoggingContext model, Action< LlamaLibrary::LlamaInfrence, string, string > callback) static
Registers a completion callback function for the Llama model.
Parameters
model The logging context of the Llama model.
callback The action to be executed on completion callback.
References Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.completionCallbackAction, Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.SetCompletionCallback(), Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticCompleteCallback(), and LlamaLibrary.LoggingContext.swigCPtr.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.Start().
RegisterLogCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterLogCallback (LoggingContext model, Action< LlamaLibrary::LlamaInfrence, string > callback) static
Registers a log callback function for the Llama model.
Parameters
model The logging context of the Llama model.
callback The action to be executed on log callback.
References Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.logCallbackAction, Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.SetLogCallback(), Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticLogCallback(), and LlamaLibrary.LoggingContext.swigCPtr.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.Start().
RegisterTokenCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterTokenCallback (LoggingContext model, Action< LlamaLibrary::LlamaInfrence, string > callback) static
Registers a token callback function for the Llama model.
Parameters
model The logging context of the Llama model.
callback The action to be executed on token callback.
References Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.SetTokenCallback(), Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticTokenCallback(), LlamaLibrary.LoggingContext.swigCPtr, and Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.tokenCallbackAction.
Referenced by Assets.StyledLines.Runtime.LlamaInfrenceUnity.ModelController.ModelController(), and Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.Start().
SetCompletionCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.SetCompletionCallback (IntPtr ctx, CompleteCallback callback) private
Sets the completion callback function for the native library.
Parameters
ctx The context pointer.
callback The callback function to register.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterCompletionCallback().
SetLogCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.SetLogCallback (IntPtr ctx, LogCallback callback) private
Sets the log callback function for the native library.
Parameters
ctx The context pointer.
callback The callback function to register.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterLogCallback().
SetTokenCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.SetTokenCallback (IntPtr ctx, TokenCallback callback) private
Sets the token callback function for the native library.
Parameters
ctx The context pointer.
callback The callback function to register.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterTokenCallback().
StaticCompleteCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticCompleteCallback (IntPtr ctx, IntPtr input_message, int input_length, IntPtr output_message, int output_length) static private
Static method to handle the completion callback from the native library.
Parameters
ctx The context pointer.
input_message The input message pointer.
input_length The length of the input message.
output_message The output message pointer.
output_length The length of the output message.
References Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.completionCallbackAction.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterCompletionCallback().
StaticLogCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticLogCallback (IntPtr ctx, IntPtr message, int length) static private
Static method to handle the log callback from the native library.
Parameters
ctx The context pointer.
message The message pointer.
length The length of the message.
References Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.logCallbackAction.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterLogCallback().
StaticTokenCallback()
static void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticTokenCallback (IntPtr ctx, IntPtr message, int length) static private
Static method to handle the token callback from the native library.
Parameters
ctx The context pointer.
message The message pointer.
length The length of the message.
References Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.tokenCallbackAction.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterTokenCallback().
TokenCallback()
delegate void Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.TokenCallback (IntPtr ctx, IntPtr message, int length) private
Delegate for handling token callback functions from the native library.
Member Data Documentation
completionCallbackAction
Action<LlamaLibrary.LlamaInfrence, string, string> Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.completionCallbackAction static private
Stores the action to be executed when the completion callback is triggered.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterCompletionCallback(), and Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticCompleteCallback().
LIBRARY_NAME
const string Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.LIBRARY_NAME = "libllama_lib" static
Specifies the name of the native library based on the platform.
logCallbackAction
Action<LlamaLibrary.LlamaInfrence, string> Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.logCallbackAction static private
Stores the action to be executed when the log callback is triggered.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterLogCallback(), and Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticLogCallback().
tokenCallbackAction
Action<LlamaLibrary.LlamaInfrence, string> Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.tokenCallbackAction static private
Stores the action to be executed when the token callback is triggered.
Referenced by Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.RegisterTokenCallback(), and Assets.StyledLines.Runtime.LlamaInfrence.CallbackWrapper.StaticTokenCallback().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/CallbackWrapper.cs