StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured Class Reference
Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured Class Reference
Public Attributes
RunModelAsync StateController
List< Selectable > UiObjects
Private Member Functions
void OnDestroy ()
void OnStateChanged (RunModelAsync.State state)
void SetUIObjectsActive (bool isActive)
void Start ()
Member Function Documentation
OnDestroy()
void Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.OnDestroy () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnStateChanged, Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.OnStateChanged(), and Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.StateController.
OnStateChanged()
void Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.OnStateChanged (RunModelAsync::State state) private
References Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.SetUIObjectsActive().
Referenced by Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.Start().
SetUIObjectsActive()
void Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.SetUIObjectsActive (bool isActive) private
References Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.UiObjects.
Referenced by Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.OnStateChanged(), and Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.Start().
Start()
void Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.Start () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnStateChanged, Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.OnStateChanged(), Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.SetUIObjectsActive(), and Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.StateController.
Member Data Documentation
StateController
RunModelAsync Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.StateController
Referenced by Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.Start().
UiObjects
List<Selectable> Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.UiObjects
Referenced by Assets.StyledLines.Runtime.UIHelpers.DisableWhileNotConfigured.SetUIObjectsActive().
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/DisableWhileNotConfigured.cs