StyledLines from testedlines.com: C# docs: LlamaLibrary.libllama_libPINVOKE.SWIGPendingException Class Reference
LlamaLibrary.libllama_libPINVOKE.SWIGPendingException Class Reference
Static Public Member Functions
static global::System.Exception Retrieve ()
static void Set (global::System.Exception e)
Properties
static bool Pending [get]
Static Private Attributes
static int numExceptionsPending = 0
static global::System.Exception pendingException = null
Member Function Documentation
Retrieve()
static global.System.Exception LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve () static
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.numExceptionsPending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.pendingException.
Referenced by LlamaLibrary.Strings.Add(), LlamaLibrary.StringsAndFloats.Add(), LlamaLibrary.LlamaControlVectorLoadInfos.Add(), LlamaLibrary.Int32s.AddRange(), LlamaLibrary.LlamaControlVectorLoadInfos.AddRange(), LlamaLibrary.Strings.AddRange(), LlamaLibrary.StringsAndFloats.AddRange(), LlamaLibrary.Strings.Contains(), LlamaLibrary.LlamaInfrence.Echo(), LlamaLibrary.LlamaInfrence.Generate(), LlamaLibrary.AsyncLlamaInfrence.GenerateAsync(), LlamaLibrary.Int32s.getitem(), LlamaLibrary.LlamaControlVectorLoadInfos.getitem(), LlamaLibrary.Strings.getitem(), LlamaLibrary.StringsAndFloats.getitem(), LlamaLibrary.Int32s.getitemcopy(), LlamaLibrary.LlamaControlVectorLoadInfos.getitemcopy(), LlamaLibrary.Strings.getitemcopy(), LlamaLibrary.StringsAndFloats.getitemcopy(), LlamaLibrary.LlamaInfrence.GetParameters(), LlamaLibrary.Int32s.GetRange(), LlamaLibrary.LlamaControlVectorLoadInfos.GetRange(), LlamaLibrary.Strings.GetRange(), LlamaLibrary.StringsAndFloats.GetRange(), LlamaLibrary.Strings.IndexOf(), LlamaLibrary.Int32s.Insert(), LlamaLibrary.Strings.Insert(), LlamaLibrary.StringsAndFloats.Insert(), LlamaLibrary.LlamaControlVectorLoadInfos.Insert(), LlamaLibrary.Int32s.InsertRange(), LlamaLibrary.LlamaControlVectorLoadInfos.InsertRange(), LlamaLibrary.Strings.InsertRange(), LlamaLibrary.StringsAndFloats.InsertRange(), LlamaLibrary.Int32s.Int32s(), LlamaLibrary.Int32s.Int32s(), LlamaLibrary.Strings.LastIndexOf(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), LlamaLibrary.LlamaInfrence.LlamaInfrence(), LlamaLibrary.Strings.Remove(), LlamaLibrary.Int32s.RemoveAt(), LlamaLibrary.LlamaControlVectorLoadInfos.RemoveAt(), LlamaLibrary.Strings.RemoveAt(), LlamaLibrary.StringsAndFloats.RemoveAt(), LlamaLibrary.Int32s.RemoveRange(), LlamaLibrary.LlamaControlVectorLoadInfos.RemoveRange(), LlamaLibrary.Strings.RemoveRange(), LlamaLibrary.StringsAndFloats.RemoveRange(), LlamaLibrary.Int32s.Repeat(), LlamaLibrary.Strings.Repeat(), LlamaLibrary.StringsAndFloats.Repeat(), LlamaLibrary.LlamaControlVectorLoadInfos.Repeat(), LlamaLibrary.Int32s.Reverse(), LlamaLibrary.LlamaControlVectorLoadInfos.Reverse(), LlamaLibrary.Strings.Reverse(), LlamaLibrary.StringsAndFloats.Reverse(), LlamaLibrary.FileWrapper.Save(), LlamaLibrary.FileWrapper.Save(), LlamaLibrary.FileWrapper.Save(), LlamaLibrary.Int32s.setitem(), LlamaLibrary.Strings.setitem(), LlamaLibrary.StringsAndFloats.setitem(), LlamaLibrary.LlamaControlVectorLoadInfos.setitem(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingApplicationException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentNullException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentOutOfRangeException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArithmeticException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingDivideByZeroException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingIndexOutOfRangeException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingInvalidCastException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingInvalidOperationException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingIOException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingNullReferenceException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingOutOfMemoryException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingOverflowException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingSystemException(), LlamaLibrary.Int32s.SetRange(), LlamaLibrary.LlamaControlVectorLoadInfos.SetRange(), LlamaLibrary.Strings.SetRange(), LlamaLibrary.StringsAndFloats.SetRange(), LlamaLibrary.AsyncLlamaInfrence.SetupAsync(), LlamaLibrary.StringAndFloat.StringAndFloat(), LlamaLibrary.StringAndFloat.StringAndFloat(), LlamaLibrary.Strings.Strings(), LlamaLibrary.Strings.Strings(), LlamaLibrary.StringsAndFloats.StringsAndFloats(), and LlamaLibrary.StringsAndFloats.StringsAndFloats().
Set()
static void LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set (global::System::Exception e) static
References LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.numExceptionsPending, and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.pendingException.
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingApplicationException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentNullException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArgumentOutOfRangeException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingArithmeticException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingDivideByZeroException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingIndexOutOfRangeException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingInvalidCastException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingInvalidOperationException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingIOException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingNullReferenceException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingOutOfMemoryException(), LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingOverflowException(), and LlamaLibrary.libllama_libPINVOKE.SWIGExceptionHelper.SetPendingSystemException().
Member Data Documentation
numExceptionsPending
int LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.numExceptionsPending = 0 static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
pendingException
global.System.Exception LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.pendingException = null static private
Referenced by LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Retrieve(), and LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Set().
Property Documentation
Pending
bool LlamaLibrary.libllama_libPINVOKE.SWIGPendingException.Pending static get
Referenced by LlamaLibrary.Strings.Add(), LlamaLibrary.StringsAndFloats.Add(), LlamaLibrary.LlamaControlVectorLoadInfos.Add(), LlamaLibrary.Int32s.AddRange(), LlamaLibrary.LlamaControlVectorLoadInfos.AddRange(), LlamaLibrary.Strings.AddRange(), LlamaLibrary.StringsAndFloats.AddRange(), LlamaLibrary.Strings.Contains(), LlamaLibrary.LlamaInfrence.Echo(), LlamaLibrary.LlamaInfrence.Generate(), LlamaLibrary.AsyncLlamaInfrence.GenerateAsync(), LlamaLibrary.Int32s.getitem(), LlamaLibrary.LlamaControlVectorLoadInfos.getitem(), LlamaLibrary.Strings.getitem(), LlamaLibrary.StringsAndFloats.getitem(), LlamaLibrary.Int32s.getitemcopy(), LlamaLibrary.LlamaControlVectorLoadInfos.getitemcopy(), LlamaLibrary.Strings.getitemcopy(), LlamaLibrary.StringsAndFloats.getitemcopy(), LlamaLibrary.LlamaInfrence.GetParameters(), LlamaLibrary.Int32s.GetRange(), LlamaLibrary.LlamaControlVectorLoadInfos.GetRange(), LlamaLibrary.Strings.GetRange(), LlamaLibrary.StringsAndFloats.GetRange(), LlamaLibrary.Strings.IndexOf(), LlamaLibrary.Int32s.Insert(), LlamaLibrary.Strings.Insert(), LlamaLibrary.StringsAndFloats.Insert(), LlamaLibrary.LlamaControlVectorLoadInfos.Insert(), LlamaLibrary.Int32s.InsertRange(), LlamaLibrary.LlamaControlVectorLoadInfos.InsertRange(), LlamaLibrary.Strings.InsertRange(), LlamaLibrary.StringsAndFloats.InsertRange(), LlamaLibrary.Int32s.Int32s(), LlamaLibrary.Int32s.Int32s(), LlamaLibrary.Strings.LastIndexOf(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), LlamaLibrary.LlamaControlVectorLoadInfos.LlamaControlVectorLoadInfos(), LlamaLibrary.LlamaInfrence.LlamaInfrence(), LlamaLibrary.Strings.Remove(), LlamaLibrary.Int32s.RemoveAt(), LlamaLibrary.LlamaControlVectorLoadInfos.RemoveAt(), LlamaLibrary.Strings.RemoveAt(), LlamaLibrary.StringsAndFloats.RemoveAt(), LlamaLibrary.Int32s.RemoveRange(), LlamaLibrary.LlamaControlVectorLoadInfos.RemoveRange(), LlamaLibrary.Strings.RemoveRange(), LlamaLibrary.StringsAndFloats.RemoveRange(), LlamaLibrary.Int32s.Repeat(), LlamaLibrary.Strings.Repeat(), LlamaLibrary.StringsAndFloats.Repeat(), LlamaLibrary.LlamaControlVectorLoadInfos.Repeat(), LlamaLibrary.Int32s.Reverse(), LlamaLibrary.LlamaControlVectorLoadInfos.Reverse(), LlamaLibrary.Strings.Reverse(), LlamaLibrary.StringsAndFloats.Reverse(), LlamaLibrary.FileWrapper.Save(), LlamaLibrary.FileWrapper.Save(), LlamaLibrary.FileWrapper.Save(), LlamaLibrary.Int32s.setitem(), LlamaLibrary.Strings.setitem(), LlamaLibrary.StringsAndFloats.setitem(), LlamaLibrary.LlamaControlVectorLoadInfos.setitem(), LlamaLibrary.Int32s.SetRange(), LlamaLibrary.LlamaControlVectorLoadInfos.SetRange(), LlamaLibrary.Strings.SetRange(), LlamaLibrary.StringsAndFloats.SetRange(), LlamaLibrary.AsyncLlamaInfrence.SetupAsync(), LlamaLibrary.StringAndFloat.StringAndFloat(), LlamaLibrary.StringAndFloat.StringAndFloat(), LlamaLibrary.Strings.Strings(), LlamaLibrary.Strings.Strings(), LlamaLibrary.StringsAndFloats.StringsAndFloats(), and LlamaLibrary.StringsAndFloats.StringsAndFloats().
The documentation for this class was generated from the following file:
StyledLines/Runtime/LlamaInfrence/libllama_libPINVOKE.cs