StyledLines from testedlines.com: C# docs: PrintStopwatchScore Class Reference
PrintStopwatchScore Class Reference
Public Attributes
RunModelAsync StateController
TMP_Text UiObject
Private Member Functions
void OnDestroy ()
void OnStateChangedDone (string text)
void OnStateChangedStart (string text)
void Start ()
Member Function Documentation
OnDestroy()
void PrintStopwatchScore.OnDestroy () private
References RunModelAsync.OnGeneratedComplete, RunModelAsync.OnGeneratedOutputChanged, OnStateChangedDone(), OnStateChangedStart(), and StateController.
OnStateChangedDone()
void PrintStopwatchScore.OnStateChangedDone (string text) private
Referenced by OnDestroy(), and Start().
OnStateChangedStart()
void PrintStopwatchScore.OnStateChangedStart (string text) private
Referenced by OnDestroy(), and Start().
Start()
void PrintStopwatchScore.Start () private
References RunModelAsync.OnGeneratedComplete, RunModelAsync.OnGeneratedOutputChanged, OnStateChangedDone(), OnStateChangedStart(), and StateController.
Member Data Documentation
StateController
RunModelAsync PrintStopwatchScore.StateController
Referenced by OnDestroy(), and Start().
UiObject
TMP_Text PrintStopwatchScore.UiObject
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/PrintStopwatchScore.cs