StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper Class Reference
Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper Class Reference
Private Member Functions
void OnCharacterSelected (int selectedIndex)
void OnStyleChanged (string newStyle)
void SetStyleInputField (string style)
void Start ()
Private Attributes
TMP_Dropdown characterDropdown
DialogManager dialogManager
TMP_InputField styleInputField
Member Function Documentation
OnCharacterSelected()
void Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnCharacterSelected (int selectedIndex) private
References Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.characterDropdown, Assets.StyledLines.Runtime.DialogUtils.DialogManager.Characters, Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.dialogManager, and Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.SetStyleInputField().
Referenced by Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start().
OnStyleChanged()
void Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnStyleChanged (string newStyle) private
References Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.characterDropdown, Assets.StyledLines.Runtime.DialogUtils.DialogManager.Characters, and Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.dialogManager.
Referenced by Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start().
SetStyleInputField()
void Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.SetStyleInputField (string style) private
Referenced by Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnCharacterSelected(), and Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start().
Start()
void Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start () private
References Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.characterDropdown, Assets.StyledLines.Runtime.DialogUtils.DialogManager.Characters, Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.dialogManager, Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnCharacterSelected(), Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnStyleChanged(), Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.SetStyleInputField(), and Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.styleInputField.
Member Data Documentation
characterDropdown
TMP_Dropdown Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.characterDropdown private
Referenced by Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnCharacterSelected(), Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnStyleChanged(), and Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start().
dialogManager
DialogManager Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.dialogManager private
Referenced by Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnCharacterSelected(), Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.OnStyleChanged(), and Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start().
styleInputField
TMP_InputField Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.styleInputField private
Referenced by Assets.StyledLines.Runtime.DialogUtils.CharacterStyleMapper.Start().
The documentation for this class was generated from the following file:
StyledLines/Runtime/DialogUtils/CharacterStyleMapper.cs