StyledLines from testedlines.com: C# docs: Assets.StyledLines.Runtime.UIHelpers.PrintModelState Class Reference
Assets.StyledLines.Runtime.UIHelpers.PrintModelState Class Reference
Public Attributes
RunModelAsync StateController
TMP_Text UiObject
Private Member Functions
void OnDestroy ()
void OnStateChanged (RunModelAsync.State state)
void Start ()
Member Function Documentation
OnDestroy()
void Assets.StyledLines.Runtime.UIHelpers.PrintModelState.OnDestroy () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnStateChanged, Assets.StyledLines.Runtime.UIHelpers.PrintModelState.OnStateChanged(), and Assets.StyledLines.Runtime.UIHelpers.PrintModelState.StateController.
OnStateChanged()
void Assets.StyledLines.Runtime.UIHelpers.PrintModelState.OnStateChanged (RunModelAsync::State state) private
Referenced by Assets.StyledLines.Runtime.UIHelpers.PrintModelState.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.PrintModelState.Start().
Start()
void Assets.StyledLines.Runtime.UIHelpers.PrintModelState.Start () private
References Assets.StyledLines.Runtime.LlamaInfrenceUnity.RunModelAsync.OnStateChanged, Assets.StyledLines.Runtime.UIHelpers.PrintModelState.OnStateChanged(), and Assets.StyledLines.Runtime.UIHelpers.PrintModelState.StateController.
Member Data Documentation
StateController
RunModelAsync Assets.StyledLines.Runtime.UIHelpers.PrintModelState.StateController
Referenced by Assets.StyledLines.Runtime.UIHelpers.PrintModelState.OnDestroy(), and Assets.StyledLines.Runtime.UIHelpers.PrintModelState.Start().
UiObject
TMP_Text Assets.StyledLines.Runtime.UIHelpers.PrintModelState.UiObject
The documentation for this class was generated from the following file:
StyledLines/Runtime/UIHelpers/PrintModelState.cs