var dir_196c20204c01b5987ec1cd6c8f354df9 =
[
    [ "AsyncLlamaInfrence.cs", "_async_llama_infrence_8cs.html", "_async_llama_infrence_8cs" ],
    [ "CallbackWrapper.cs", "_callback_wrapper_8cs.html", "_callback_wrapper_8cs" ],
    [ "dimre_method.cs", "dimre__method_8cs.html", "dimre__method_8cs" ],
    [ "FileWrapper.cs", "_file_wrapper_8cs.html", "_file_wrapper_8cs" ],
    [ "gpt_params.cs", "gpt__params_8cs.html", "gpt__params_8cs" ],
    [ "Int32s.cs", "_int32s_8cs.html", "_int32s_8cs" ],
    [ "libllama_lib.cs", "libllama__lib_8cs.html", "libllama__lib_8cs" ],
    [ "libllama_libPINVOKE.cs", "libllama__lib_p_i_n_v_o_k_e_8cs.html", "libllama__lib_p_i_n_v_o_k_e_8cs" ],
    [ "llama_sampler_type.cs", "llama__sampler__type_8cs.html", "llama__sampler__type_8cs" ],
    [ "llama_sampling_params.cs", "llama__sampling__params_8cs.html", "llama__sampling__params_8cs" ],
    [ "LlamaControlVectorLoadInfos.cs", "_llama_control_vector_load_infos_8cs.html", "_llama_control_vector_load_infos_8cs" ],
    [ "LlamaInfrence.cs", "_llama_infrence_8cs.html", "_llama_infrence_8cs" ],
    [ "LoggingContext.cs", "_logging_context_8cs.html", "_logging_context_8cs" ],
    [ "StringAndFloat.cs", "_string_and_float_8cs.html", "_string_and_float_8cs" ],
    [ "Strings.cs", "_strings_8cs.html", "_strings_8cs" ],
    [ "StringsAndFloats.cs", "_strings_and_floats_8cs.html", "_strings_and_floats_8cs" ],
    [ "SWIGTYPE_llama_attention_type.cs", "_s_w_i_g_t_y_p_e__llama__attention__type_8cs.html", "_s_w_i_g_t_y_p_e__llama__attention__type_8cs" ],
    [ "SWIGTYPE_llama_pooling_type.cs", "_s_w_i_g_t_y_p_e__llama__pooling__type_8cs.html", "_s_w_i_g_t_y_p_e__llama__pooling__type_8cs" ],
    [ "SWIGTYPE_llama_rope_scaling_type.cs", "_s_w_i_g_t_y_p_e__llama__rope__scaling__type_8cs.html", "_s_w_i_g_t_y_p_e__llama__rope__scaling__type_8cs" ],
    [ "SWIGTYPE_llama_split_mode.cs", "_s_w_i_g_t_y_p_e__llama__split__mode_8cs.html", "_s_w_i_g_t_y_p_e__llama__split__mode_8cs" ],
    [ "SWIGTYPE_p_AsyncLlamaInfrence__LlamaAsyncImpl.cs", "_s_w_i_g_t_y_p_e__p___async_llama_infrence_____llama_async_impl_8cs.html", "_s_w_i_g_t_y_p_e__p___async_llama_infrence_____llama_async_impl_8cs" ],
    [ "SWIGTYPE_p_float.cs", "_s_w_i_g_t_y_p_e__p__float_8cs.html", "_s_w_i_g_t_y_p_e__p__float_8cs" ],
    [ "SWIGTYPE_p_ggml_backend_sched_eval_callback.cs", "_s_w_i_g_t_y_p_e__p__ggml__backend__sched__eval__callback_8cs.html", "_s_w_i_g_t_y_p_e__p__ggml__backend__sched__eval__callback_8cs" ],
    [ "SWIGTYPE_p_ggml_numa_strategy.cs", "_s_w_i_g_t_y_p_e__p__ggml__numa__strategy_8cs.html", "_s_w_i_g_t_y_p_e__p__ggml__numa__strategy_8cs" ],
    [ "SWIGTYPE_p_llama_control_vector_load_info.cs", "_s_w_i_g_t_y_p_e__p__llama__control__vector__load__info_8cs.html", "_s_w_i_g_t_y_p_e__p__llama__control__vector__load__info_8cs" ],
    [ "SWIGTYPE_p_llama_sampling_params.cs", "_s_w_i_g_t_y_p_e__p__llama__sampling__params_8cs.html", "_s_w_i_g_t_y_p_e__p__llama__sampling__params_8cs" ],
    [ "SWIGTYPE_p_LlamaInfrence__LlamaImpl.cs", "_s_w_i_g_t_y_p_e__p___llama_infrence_____llama_impl_8cs.html", "_s_w_i_g_t_y_p_e__p___llama_infrence_____llama_impl_8cs" ],
    [ "SWIGTYPE_p_LoggingContext__LoggingContextPimpl.cs", "_s_w_i_g_t_y_p_e__p___logging_context_____logging_context_pimpl_8cs.html", "_s_w_i_g_t_y_p_e__p___logging_context_____logging_context_pimpl_8cs" ],
    [ "SWIGTYPE_p_std__unordered_mapT_llama_token_float_t.cs", "_s_w_i_g_t_y_p_e__p__std____unordered__map_t__llama__token__float__t_8cs.html", "_s_w_i_g_t_y_p_e__p__std____unordered__map_t__llama__token__float__t_8cs" ],
    [ "SWIGTYPE_p_std__vectorT_llama_model_kv_override_t.cs", "_s_w_i_g_t_y_p_e__p__std____vector_t__llama__model__kv__override__t_8cs.html", "_s_w_i_g_t_y_p_e__p__std____vector_t__llama__model__kv__override__t_8cs" ],
    [ "SWIGTYPE_p_std__vectorT_llama_sampler_type_t.cs", "_s_w_i_g_t_y_p_e__p__std____vector_t__llama__sampler__type__t_8cs.html", "_s_w_i_g_t_y_p_e__p__std____vector_t__llama__sampler__type__t_8cs" ],
    [ "SWIGTYPE_p_std__vectorT_llama_token_t.cs", "_s_w_i_g_t_y_p_e__p__std____vector_t__llama__token__t_8cs.html", "_s_w_i_g_t_y_p_e__p__std____vector_t__llama__token__t_8cs" ],
    [ "SWIGTYPE_p_std__vectorT_std__tupleT_std__string_float_t_t.cs", "_s_w_i_g_t_y_p_e__p__std____vector_t__std____tuple_t__std____string__float__t__t_8cs.html", "_s_w_i_g_t_y_p_e__p__std____vector_t__std____tuple_t__std____string__float__t__t_8cs" ],
    [ "SWIGTYPE_p_void.cs", "_s_w_i_g_t_y_p_e__p__void_8cs.html", "_s_w_i_g_t_y_p_e__p__void_8cs" ]
];